package de.hhu.propra.chicken.repository;

public class LsfPage {

  static String THEORETISCHE_INFORMATIK_PAGE = """

      <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
      "http://www.w3.org/TR/html4/loose.dtd">\s
      <html lang="de">
      <head>
      <!-- Generated by node "capuma-lsf-prod-as04" in cluster "cl_p" 
      using thread ajp-nio-192.168.164.244-8009-exec-10 -->
      <title>\s
      \s

      - Vorlesung/ Übung: Theoretische Informatik (früher: Grundlagen der Theoretischen Informatik)
      Heinrich Heine Universität Düsseldorf </title>
      <link rel="stylesheet" type="text/css" href="/qisserver/pub/QISDesign_HHU.css?1">




      <link rel="icon" href="/favicon.ico" type="image/gif">
      <link rel="top" href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=0&amp;topitem=
      " title="Top">\s
      <link rel="stylesheet" type="text/css" media="print" href="/qisserver/pub/Print.css">
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <meta http-equiv="Cache-Control" content="private,must-revalidate,no-cache,no-store">
      </head>
      <body>
      <div id="wrapper">
      <div class="unsichtbar">
      <a accesskey="1" href="#navi">Zur Seitennavigation oder mit Tastenkombination für den 
      <span lang="en">accesskey</span>-Taste und Taste 1</a>&nbsp;<br>
      <a accesskey="2" href="#lese">Zum Seiteninhalt oder mit Tastenkombination für den 
      <span lang="en">accesskey</span> und Taste 2</a>&nbsp;
      </div>
      <div class="header_hisinone">
      <div class="logo">
      <a href="https://lsf.hhu.de/qisserver/rds?state=redirect&amp;destination=http%3A%2F%2Fwww
      .hhu.de
      &amp;timestamp=1647515621830&amp;hash=b9a2ffa2d8549722d991b90920bf4f34" target="_blank">
      <img src="/QIS/images//logo_rgb_HHU.jpg" height="104" 
      alt="Heinrich Heine Universität Düsseldorf" title="Heinrich Heine Universität Düsseldorf" 
      border="0"></a>
      </div>
      <div class="services">
      <ol>
      <li>
      \s
      \s
      <a href="https://lsf.hhu.de/qisserver/rds?state=change&amp;type=6&amp;moduleParameter=seme
      sterSelec
      t&amp;nextdir=change&amp;next=SearchSelect.vm&amp;subdir=applications&amp;targettype=7&amp
      ;targetsta
      te=change&amp;getglobal=semester" id="choosesemester" title="Semester wählen ...">
      SoSe 2022
      </a>
      <img src="/QIS/images//his_strich_blau.gif" width="1" height="11" alt="">
      </li>
      <li><a href="https://lsf.hhu.de/qisserver/rds?state=helpdoc&amp;calling=helpcenter&amp;top
      item=leer
      &amp;breadCrumbSource=" title="Hilfe"> Hilfe</a> <img src="/QIS/images//his_strich_blau.gif" 
      width="1" height="11" alt=""></li>
      <li><a href="https://lsf.hhu.de/qisserver/rds?state=helpdoc&amp;calling=myhhuinfo&amp;topi
      tem=leer
      &amp;breadCrumbSource=" title="Info"> Info</a> <img src="/QIS/images//his_strich_blau.gif" 
      width="1" height="11" alt=""></li>
      <li>
      <a href="https://lsf.hhu.de/qisserver/rds?state=sitemap&amp;topitem=leer&amp;breadCrumbSo
      urce="  
      title="Sitemap">Sitemap</a>
      <img src="/QIS/images//his_strich_blau.gif" width="1" height="11" alt="">
      </li>
      </ol>
      \s
      <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=5&amp;language=en">
      <img SRC="/QIS/images/flag_en.svg" alt="Switch to english language" vspace="2" height="16" 
      width="16" style="vertical-align:text-top;" border="0" lang="en" title="Switch to english 
      language"></a>
      \s
      </div><div style="clear:both;"></div>
      </div>
      <div class="divloginstatus">
      <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=0&amp;topitem=&amp;breadCr
      umbSour
      ce=&amp;topitem=functions" title="Startseite" class="links3"><u>S</u>tartseite</a>
      <span>
      &nbsp;<img src="/QIS/images//his_strich.gif" width="1" height="11" alt="">&nbsp;
      </span>
      <a href="https://lsf.hhu.de/qisserver/rds?state=wlogin&amp;login=in&amp;breadCrumbSource=" 
      class="links3" accesskey="l"><u>A</u>nmelden</a>
      <span>
      &nbsp;<img src="/QIS/images//his_strich.gif" width="1" height="11" alt="">&nbsp;
      <div style="float:right;margin-right:5px; display:none;">
      <logout active="n" style="" class="" maxtime="30" timeoutmessage="Ihre Session-Zeit ist a
      bgelaufen. 
      Bitte melden Sie sich wieder an um weiterzuarbeiten."\s
      class5min="" class10min="" minutetext_singular="Minute" minutetext_plural="Minuten" _show
      OnMin="10">
      <logouttext>Logout in <span class="boldMin" id="min">[min]</span> [minutetext]</logouttext>
      </logout>
      </div>
      </div>
      <div class="divlinks">
      <a name="navi"></a>
      <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=8&amp;
      topitem=lectures&amp;breadCrumbSource="
      class="links2visited ">Veranstaltungen</a>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=8&amp;
      topitem=facilities&amp;breadCrumbSource="
      class="links2 ">Räume und Gebäude</a>
      &nbsp;&nbsp;&nbsp;&nbsp;
      </div>
      <div class="breadcrumb">
      Sie sind hier:
      <strong>Startseite</strong>
      <img src="/QIS/images/next.svg" alt="" border="0">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;
      search=1&amp;category=veranstaltung.browse&amp;navigationPosition=lectures%2Clectureind
      ex&amp;
      breadcrumb=lectureindex&amp;topitem=lectures&amp;subitem=lectureindex">Veranstaltungsver
      zeichnis
      </a>
      </div>
      <div class="divcontent">
      \s
      <div id="makronavigation">\s
      <ul class="menue">\s
      <li class="menueListStyle">
      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;category=veranstaltung.
      browse&amp;navigationPosition=lectures%2Clectureindex&amp;breadcrumb=lectureindex&amp;
      topitem=lectures&amp;subitem=lectureindex" class="auflistung " target='_self'>Veranstaltungsv
      erzeichnis</a>
      </li>
      <li class="menueListStyle">
      <a href="https://lsf.hhu.de/qisserver/rds?state=change&amp;type=5&amp;moduleParameter=veranst
      ltungSearch&amp;nextdir=change&amp;next=search.vm&amp;subdir=veranstaltung&amp;_form=display
      &amp;function=search&amp;clean=y&amp;category=veranstaltung.search&amp;navigationPosition=lec
      tures%2CsearchLectures&amp;breadcrumb=searchLectures&amp;topitem=lectures&amp;subitem=searchL
      ectures" class="auflistung " target='_self'>Suche nach Veranstaltungen</a>
      </li>
      <li class="menueListStyle">


      <a href="https://lsf.hhu.de/qisserver/rds?state=currentLectures&amp;type=0&amp;next=Cur
      rentLec
      tures.vm&amp;nextdir=ressourcenManager&amp;navigationPosition=lectures%2CcurrentLecture
      s&amp;br
      eadcrumb=currentLectures&amp;topitem=lectures&amp;subitem=currentLectures&amp;asi=" cla
      ss="aufl
      istung " target='_self'>Veranstaltungen - tagesaktuell</a>
      </li>





      <li class="menueListStyle">


      <a href="https://lsf.hhu.de/qisserver/rds?state=currentLectures&amp;type=1&amp;next=Cu
      rrentLec
      tures.vm&amp;nextdir=ressourcenManager&amp;navigationPosition=lectures%2CcanceledLectu
      res&amp;b
      readcrumb=canceledLectures&amp;topitem=lectures&amp;subitem=canceledLectures&amp;asi=" 
      class="au
      flistung " target='_self'>Ausfallende Veranstaltungen</a>
      </li>
      <li class="menueListStyleCloseMenu">
      <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=9&amp;menu_open=n" 
      class="auflist
      ung " target='_self'>Navigation ausblenden</a>
      </li>
      </ul>
      &nbsp; </div>


      \s
      <div class="content">



      <a name="lese"></a>




      <form class="form" action="https://lsf.hhu.de/qisserver/rds?state=wplan&amp;search=ver&amp
      ;act=a
      dd" method="post">


      <h1>
      <a href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAo40lEQVR4X
      u2Uwa7l
      SLIj+/9/emaR
      m2oDiedMKlxH1WEANwkjXdJNnP/8v8vlcvkI/+E/XC6Xy69yf7Aul8tnuD9Yl8vlM9wfrMvl8hnu
      D9blcvkM9wfrcrl8hvuDdblcPsP9wbpcLp/h/mBdLpfPcH+wLpfLZ7g/WJfL5TPcH6zL5fIZ7g/W
      5XL5DPcH63K5fIb7g3W5XD7D/cG6XC6f4f5gXS6Xz3B/sC6Xy2e4P1iXy+Uz3B+sy+XyGe4P1uVy
      +Qz3B+tyuXyG+4N1uVw+w/3Bulwun+H+YF0ul89wf7Aul8tnWP3B+s9//vMzeRruJzfYc2ngVrs3
      hTfdXTqJN82vw+d1z0znzWyzepEv+2aehvvJDfZcGrjV7k3hTXeXTuJN8+vwed0z03kz26xe5Mu+
      mafhfnKDPZcGbrV7U3jT3aWTeNP8Onxe98x03sw2qxf5sm/mabif3GDPpYFb7d4U3nR36STeNL8O
      n9c9M503s83qRb7sm3ka7ic32HNp4Fa7N4U33V06iTfNr8Pndc9M581ss3qRL7v1wrzp7tI5kSns
      vdltoqDjvAbuuxt0kijotFHQcd7T8ObW3X+yepEvu/XCvOnu0jmRKey92W2ioOO8Bu67G3SSKOi0
      UdBx3tPw5tbdf7J6kS+79cK86e7SOZEp7L3ZbaKg47wG7rsbdJIo6LRR0HHe0/Dm1t1/snqRL7v1
      wrzp7tI5kSnsvdltoqDjvAbuuxt0kijotFHQcd7T8ObW3X+yepEvu/XCvOnu0jmRKey92W2ioOO8
      Bu67G3SSKOi0UdBx3tPw5tbdf7J6kS/rXphOEgUd5zVw392g47wp3GqjoHMiCjpveioN3HJR0Em8
      aRR0nHeS1Yt8WffCdJIo6DivgfvuBh3nTeFWGwWdE1HQedNTaeCWi4JO4k2joOO8k6xe5Mu6F6aT
      REHHeQ3cdzfoOG8Kt9oo6JyIgs6bnkoDt1wUdBJvGgUd551k9SJf1r0wnSQKOs5r4L67Qcd5U7jV
      RkHnRBR03vRUGrjloqCTeNMo6DjvJKsX+bLuhekkUdBxXgP33Q06zpvCrTYKOieioPOmp9LALRcF
      ncSbRkHHeSdZvciXdS9MJ4mCTusp2Eu6Cm4le+y1XRUFHRcFHedN4Vayx57r0nFR0HGegj3XpZNE
      Qcd5J1m9yJd1L0wniYJO6ynYS7oKbiV77LVdFQUdFwUd503hVrLHnuvScVHQcZ6CPdelk0RBx3kn
      Wb3Il3UvTCeJgk7rKdhLugpuJXvstV0VBR0XBR3nTeFWssee69JxUdBxnoI916WTREHHeSdZvciX
      dS9MJ4mCTusp2Eu6Cm4le+y1XRUFHRcFHedN4Vayx57r0nFR0HGegj3XpZNEQcd5J1m9yJd1L0wn
      iYJO6ynYS7oKbiV77LVdFQUdFwUd503hVrLHnuvScVHQcZ6CPdelk0RBx3knWb3Il3UvTCeJgo7z
      FOwlUdBxnoK9E1HQOREFnTYN3HJ7dJzXwH13g04SBR3nnWT1Il/WvTCdJAo6zlOwl0RBx3kK9k5E
      QedEFHTaNHDL7dFxXgP33Q06SRR0nHeS1Yt8WffCdJIo6DhPwV4SBR3nKdg7EQWdE1HQadPALbdH
      x3kN3Hc36CRR0HHeSVYv8mXdC9NJoqDjPAV7SRR0nKdg70QUdE5EQadNA7fcHh3nNXDf3aCTREHH
      eSdZvciXdS9MJ4mCjvMU7CVR0HGegr0TUdA5EQWdNg3ccnt0nNfAfXeDThIFHeedZPUiX3brhXnT
      3aXjvAbuuxt0XBq45fboOG8Kt1wauJXssee6dJI0cKvdm8KbW3f/yepFvuzWC/Omu0vHeQ3cdzfo
      uDRwy+3Rcd4Ubrk0cCvZY8916SRp4Fa7N4U3t+7+k9WLfNmtF+ZNd5eO8xq4727QcWngltuj47wp
      3HJp4Fayx57r0knSwK12bwpvbt39J6sX+bJbL8yb7i4d5zVw392g49LALbdHx3lTuOXSwK1kjz3X
      pZOkgVvt3hTe3Lr7T1Yv8mW3Xpg33V06zmvgvrtBx6WBW26PjvOmcMulgVvJHnuuSydJA7favSm8
      uXX3n6xe5Mu+GQWd6/2BzvX+QOdN761ss3qRL/tmFHSu9wc61/sDnTe9t7LN6kW+7JtR0LneH+hc
      7w903vTeyjarF/myb0ZB53p/oHO9P9B503sr26xe5Mu+GQWd6/2BzvX+QOdN761ss3/xY/AP5P5I
      dJynYM916byZBm65PTqJN83TcL/N5b+5X+T/gP+B3H8iOs5TsOe6dN5MA7fcHp3Em+ZpuN/m8t/c
      L/J/wP9A7j8RHecp2HNdOm+mgVtuj07iTfM03G9z+W/uF/k/4H8g95+IjvMU7LkunTfTwC23Ryfx
      pnka7re5/Df3i/wf8D+Q+09Ex3kK9lyXzptp4Jbbo5N40zwN99tc/pvVL8I/xoko6LRR0Ekyhb0k
      Cjpv5mm4727QaaOg00ZBZ8vbZvUp+AFOREGnjYJOkinsJVHQeTNPw313g04bBZ02Cjpb3jarT8EP
      cCIKOm0UdJJMYS+Jgs6beRruuxt02ijotFHQ2fK2WX0KfoATUdBpo6CTZAp7SRR03szTcN/doNNG
      QaeNgs6Wt83qU/ADnIiCThsFnSRT2EuioPNmnob77gadNgo6bRR0trxtVp+CHyD5COwl3SncbzOF
      PRcFnRPe05nC3olMYS9JA7dcprDnunSct83qU/ADJB+BvaQ7hfttprDnoqBzwns6U9g7kSnsJWng
      lssU9lyXjvO2WX0KfoDkI7CXdKdwv80U9lwUdE54T2cKeycyhb0kDdxymcKe69Jx3jarT8EPkHwE
      9pLuFO63mcKei4LOCe/pTGHvRKawl6SBWy5T2HNdOs7bZvUp+AGSj8Be0p3C/TZT2HNR0DnhPZ0p
      7J3IFPaSNHDLZQp7rkvHedusPgU/wIko6LSegr02U9jb6iq45fbouExhr+2qNHDL7dFxaeCW26Pj
      ss3qRb7siSjotJ6CvTZT2NvqKrjl9ui4TGGv7ao0cMvt0XFp4Jbbo+OyzepFvuyJKOi0noK9NlPY
      2+oquOX26LhMYa/tqjRwy+3RcWngltuj47LN6kW+7Iko6LSegr02U9jb6iq45fbouExhr+2qNHDL
      7dFxaeCW26Pjss3qRb7siSjotJ6CvTZT2NvqKrjl9ui4TGGv7ao0cMvt0XFp4Jbbo+OyzepFvqx7
      YTrOexreTO6yt9X9N8Nv4qKgk0RBx3kN3G9vcCvZY89lm9WLfFn3wnSc9zS8mdxlb6v7b4bfxEVB
      J4mCjvMauN/e4Fayx57LNqsX+bLuhek472l4M7nL3lb33wy/iYuCThIFHec1cL+9wa1kjz2XbVYv
      8mXdC9Nx3tPwZnKXva3uvxl+ExcFnSQKOs5r4H57g1vJHnsu26xe5Mu6F6bjvKfhzeQue1vdfzP8
      Ji4KOkkUdJzXwP32BreSPfZctlm9yJdNoqCTeBtR0HGZwp7r0km8p/M03HeZwt6bUdBxmcKeyy+w
      +hT8AEkUdBJvIwo6LlPYc106ifd0nob7LlPYezMKOi5T2HP5BVafgh8giYJO4m1EQcdlCnuuSyfx
      ns7TcN9lCntvRkHHZQp7Lr/A6lPwAyRR0Em8jSjouExhz3XpJN7TeRruu0xh780o6LhMYc/lF1h9
      Cn6AJAo6ibcRBR2XKey5Lp3EezpPw32XKey9GQUdlynsufwCq0/BD+A+Ap0kU9hzeQs+R/Is7J3o
      0knSwC2XDXjTpYFbLgo6zlOwl3RPsvoU/ADuI9BJMoU9l7fgcyTPwt6JLp0kDdxy2YA3XRq45aKg
      4zwFe0n3JKtPwQ/gPgKdJFPYc3kLPkfyLOyd6NJJ0sAtlw1406WBWy4KOs5TsJd0T7L6FPwA7iPQ
      STKFPZe34HMkz8LeiS6dJA3cctmAN10auOWioOM8BXtJ9ySrT8EP4D4CnSRT2HN5Cz5H8izsnejS
      SdLALZcNeNOlgVsuCjrOU7CXdE+y+hT8AMlHYM916SSZwl7bVWnglksDt5I99pLuBny2E3ka7rso
      6CTZZvUiXzZ5YfZcl06SKey1XZUGbrk0cCvZYy/pbsBnO5Gn4b6Lgk6SbVYv8mWTF2bPdekkmcJe
      21Vp4JZLA7eSPfaS7gZ8thN5Gu67KOgk2Wb1Il82eWH2XJdOkinstV2VBm65NHAr2WMv6W7AZzuR
      p+G+i4JOkm1WL/Jlkxdmz3XpJJnCXttVaeCWSwO3kj32ku4GfLYTeRruuyjoJNlm9SJf1mUKey4N
      3Nrao9N6U7iV7LHnunQSr8kU9lyXjouCTuI1aeBWu/c3rF7ky7pMYc+lgVtbe3Rabwq3kj32XJdO
      4jWZwp7r0nFR0Em8Jg3cavf+htWLfFmXKey5NHBra49O603hVrLHnuvSSbwmU9hzXTouCjqJ16SB
      W+3e37B6kS/rMoU9lwZube3Rab0p3Er22HNdOonXZAp7rkvHRUEn8Zo0cKvd+xtWL/JlXaaw59LA
      ra09Oq03hVvJHnuuSyfxmkxhz3XpuCjoJF6TBm61e3/D6kW+rHthOs6bwq0kCjptprCXREHHeQr2
      XJeO8xq47zKFvSQKOltR0GmzzepFvqx7YTrOm8KtJAo6baawl0RBx3kK9lyXjvMauO8yhb0kCjpb
      UdBps83qRb6se2E6zpvCrSQKOm2msJdEQcd5CvZcl47zGrjvMoW9JAo6W1HQabPN6kW+rHthOs6b
      wq0kCjptprCXREHHeQr2XJeO8xq47zKFvSQKOltR0GmzzepFvqx7YTrOm8KtJAo6baawl0RBx3kK
      9lyXjvMauO8yhb0kCjpbUdBps83qRb5sEgUd5zVwf+uGSgO3kj32TnTptJnCXtJVcOvEnoqCjouC
      jvO2WX0KfoAkCjrOa+D+1g2VBm4le+yd6NJpM4W9pKvg1ok9FQUdFwUd522z+hT8AEkUdJzXwP2t
      GyoN3Er22DvRpdNmCntJV8GtE3sqCjouCjrO22b1KfgBkijoOK+B+1s3VBq4leyxd6JLp80U9pKu
      glsn9lQUdFwUdJy3zepT8AMkUdBxXgP3t26oNHAr2WPvRJdOmynsJV0Ft07sqSjouCjoOG+b1afg
      B3BR0HFR0HGegr2tbgNvuijotJ6CPdel47wp3EqioOO8KdxK9tg70aXjvJOsXuTLuijouCjoOE/B
      3la3gTddFHRaT8Ge69Jx3hRuJVHQcd4UbiV77J3o0nHeSVYv8mVdFHRcFHScp2Bvq9vAmy4KOq2n
      YM916ThvCreSKOg4bwq3kj32TnTpOO8kqxf5si4KOi4KOs5TsLfVbeBNFwWd1lOw57p0nDeFW0kU
      dJw3hVvJHnsnunScd5LVi3xZFwUdFwUd5ynY2+o28KaLgk7rKdhzXTrOm8KtJAo6zpvCrWSPvRNd
      Os47yepFvqx7YTqt9zS8mdxlL+kquJVkA950UdBxnoI9l7fgc5x4Fu67TGEv6T7F6kW+rHthOq33
      NLyZ3GUv6Sq4lWQD3nRR0HGegj2Xt+BznHgW7rtMYS/pPsXqRb6se2E6rfc0vJncZS/pKriVZAPe
      dFHQcZ6CPZe34HOceBbuu0xhL+k+xepFvqx7YTqt9zS8mdxlL+kquJVkA950UdBxnoI9l7fgc5x4
      Fu67TGEv6T7F6kW+rHthOq33NLyZ3GUv6Sq4lWQD3nRR0HGegj2Xt+BznHgW7rtMYS/pPsXqRb7s
      /2KmsPdmt8nTcD+Jgk7iNVHQab0p3HL5BVafgh/gfzFT2Huz2+RpuJ9EQSfxmijotN4Ubrn8AqtP
      wQ/wv5gp7L3ZbfI03E+ioJN4TRR0Wm8Kt1x+gdWn4Af4X8wU9t7sNnka7idR0Em8Jgo6rTeFWy6/
      wOpT8AP8L2YKe292mzwN95Mo6CReEwWd1pvCLZdfYPUp+AGSj8Ce69JxnoK9JFPYa7tPR0HHeQr2
      XJdO4qko6DivgfvtDW65KOg4T8Fe0j3J6lPwAyQfgT3XpeM8BXtJprDXdp+Ogo7zFOy5Lp3EU1HQ
      cV4D99sb3HJR0HGegr2ke5LVp+AHSD4Ce65Lx3kK9pJMYa/tPh0FHecp2HNdOomnoqDjvAbutze4
      5aKg4zwFe0n3JKtPwQ+QfAT2XJeO8xTsJZnCXtt9Ogo6zlOw57p0Ek9FQcd5Ddxvb3DLRUHHeQr2
      ku5JVp+CHyD5COy5Lh3nKdhLMoW9tvt0FHScp2DPdekknoqCjvMauN/e4JaLgo7zFOwl3ZOsPgU/
      gIuCzs2fNHDL7dE5kSnsJV0Ft1wUdE54T2cKey7brF7ky7oo6Nz8SQO33B6dE5nCXtJVcMtFQeeE
      93SmsOeyzepFvqyLgs7NnzRwy+3ROZEp7CVdBbdcFHROeE9nCnsu26xe5Mu6KOjc/EkDt9wenROZ
      wl7SVXDLRUHnhPd0prDnss3qRb6si4LOzZ80cMvt0TmRKewlXQW3XBR0TnhPZwp7LtvsXwT8AG0a
      uJVEQSeJgk7iPZ0GbiVp4Fa7p+B+coO9pKvg1q/t/Q37FwE/QJsGbiVR0EmioJN4T6eBW0kauNXu
      Kbif3GAv6Sq49Wt7f8P+RcAP0KaBW0kUdJIo6CTe02ngVpIGbrV7Cu4nN9hLugpu/dre37B/EfAD
      tGngVhIFnSQKOon3dBq4laSBW+2egvvJDfaSroJbv7b3N+xfBPwAbRq4lURBJ4mCTuI9nQZuJWng
      Vrun4H5yg72kq+DWr+39DasX+bIuCjouCjqJpzKFPZcp7J2Igs6Wp2AviYJOGwWdN72ns83qRb6s
      i4KOi4JO4qlMYc9lCnsnoqCz5SnYS6Kg00ZB503v6WyzepEv66Kg46Kgk3gqU9hzmcLeiSjobHkK
      9pIo6LRR0HnTezrbrF7ky7oo6Lgo6CSeyhT2XKawdyIKOluegr0kCjptFHTe9J7ONqsX+bIuCjou
      CjqJpzKFPZcp7J2Igs6Wp2AviYJOGwWdN72ns83qRb5sEgUd503hlssU9lyXjksDt5I99pKuglvJ
      HnttprCXZAp7SVfBrSS/yuqT8aMkUdBx3hRuuUxhz3XpuDRwK9ljL+kquJXssddmCntJprCXdBXc
      SvKrrD4ZP0oSBR3nTeGWyxT2XJeOSwO3kj32kq6CW8kee22msJdkCntJV8GtJL/K6pPxoyRR0HHe
      FG65TGHPdem4NHAr2WMv6Sq4leyx12YKe0mmsJd0FdxK8qusPhk/ShIFHedN4ZbLFPZcl45LA7eS
      PfaSroJbyR57baawl2QKe0lXwa0kv8rqk/GjuA9DJ/GejoLOiSjouDRw680o6DivgftJFHT+Tdlm
      9SJf1r0wncR7Ogo6J6Kg49LArTejoOO8Bu4nUdD5N2Wb1Yt8WffCdBLv6SjonIiCjksDt96Mgo7z
      GrifREHn35RtVi/yZd0L00m8p6OgcyIKOi4N3HozCjrOa+B+EgWdf1O2Wb3Il3UvTCfxno6Czoko
      6Lg0cOvNKOg4r4H7SRR0/k3ZZvUiX7bNBrzpoqCTeCob8Ka7S6eNgk7iNVHQOeFNo6DTegr2ku5T
      rF7ky7bZgDddFHQST2UD3nR36bRR0Em8Jgo6J7xpFHRaT8Fe0n2K1Yt82TYb8KaLgk7iqWzAm+4u
      nTYKOonXREHnhDeNgk7rKdhLuk+xepEv22YD3nRR0Ek8lQ14092l00ZBJ/GaKOic8KZR0Gk9BXtJ
      9ylWL/Jl22zAmy4KOomnsgFvurt02ijoJF4TBZ0T3jQKOq2nYC/pPsX+RcAP4KKgk3gqU9hzUdBx
      mcKe69JJPBUFnSRT2HNdOs6bwq0kCjrOU7DnunTa/AKvPwU/iouCTuKpTGHPRUHHZQp7rksn8VQU
      dJJMYc916ThvCreSKOg4T8Ge69Jp8wu8/hT8KC4KOomnMoU9FwUdlynsuS6dxFNR0EkyhT3XpeO8
      KdxKoqDjPAV7rkunzS/w+lPwo7go6CSeyhT2XBR0XKaw57p0Ek9FQSfJFPZcl47zpnAriYKO8xTs
      uS6dNr/A60/Bj+KioJN4KlPYc1HQcZnCnuvSSTwVBZ0kU9hzXTrOm8KtJAo6zlOw57p02vwCv/EU
      A/jx3Aek4zwFe65Lx3kN3E9usNd2VRR0Wk/BXpIGbrk9Oq33NLzp7tJx3ja/8RQD+PHcB6TjPAV7
      rkvHeQ3cT26w13ZVFHRaT8FekgZuuT06rfc0vOnu0nHeNr/xFAP48dwHpOM8BXuuS8d5DdxPbrDX
      dlUUdFpPwV6SBm65PTqt9zS86e7Scd42v/EUA/jx3Aek4zwFe65Lx3kN3E9usNd2VRR0Wk/BXpIG
      brk9Oq33NLzp7tJx3ja/8RQD+PHcB6TjPAV7rkvHeQ3cT26w13ZVFHRaT8FekgZuuT06rfc0vOnu
      0nHeNqtPwQ/QZgp7rkvHeVO45bIBb7Z3ueX26LTeFG4le+y5KOi4TGHv17LN6kW+bJsp7LkuHedN
      4ZbLBrzZ3uWW26PTelO4leyx56Kg4zKFvV/LNqsX+bJtprDnunScN4VbLhvwZnuXW26PTutN4Vay
      x56Lgo7LFPZ+LdusXuTLtpnCnuvScd4UbrlswJvtXW65PTqtN4VbyR57Lgo6LlPY+7Vss3qRL9tm
      CnuuS8d5U7jlsgFvtne55fbotN4UbiV77Lko6LhMYe/Xss3+xR+BH95FQcelgVtuj47LFPbaKOgk
      UdBp8zTc37qh0sCtdu9v2L/4I/DDuyjouDRwy+3RcZnCXhsFnSQKOm2ehvtbN1QauNXu/Q37F38E
      fngXBR2XBm65PTouU9hro6CTREGnzdNwf+uGSgO32r2/Yf/ij8AP76Kg49LALbdHx2UKe20UdJIo
      6LR5Gu5v3VBp4Fa79zfsX/wR+OFdFHRcGrjl9ui4TGGvjYJOEgWdNk/D/a0bKg3cavf+htWLfFkX
      BZ3EU5nCnssU9truRhR0Wu9peNPdpZN40yjotFHQcfkSq0/LD+WioJN4KlPYc5nCXtvdiIJO6z0N
      b7q7dBJvGgWdNgo6Ll9i9Wn5oVwUdBJPZQp7LlPYa7sbUdBpvafhTXeXTuJNo6DTRkHH5UusPi0/
      lIuCTuKpTGHPZQp7bXcjCjqt9zS86e7SSbxpFHTaKOi4fInVp+WHclHQSTyVKey5TGGv7W5EQaf1
      noY33V06iTeNgk4bBR2XL7H6tPxQLgo6Saawl3QV3GrTwC23R6fNFPZcFHRcGrjl9ugk3tOZwl7S
      3Wb1yfhRXBR0kkxhL+kquNWmgVtuj06bKey5KOi4NHDL7dFJvKczhb2ku83qk/GjuCjoJJnCXtJV
      cKtNA7fcHp02U9hzUdBxaeCW26OTeE9nCntJd5vVJ+NHcVHQSTKFvaSr4FabBm65PTptprDnoqDj
      0sAtt0cn8Z7OFPaS7jarT8aP4qKgk2QKe0lXwa02Ddxye3TaTGHPRUHHpYFbbo9O4j2dKewl3W1e
      fzJ+qPZjccvlabjvMoU9FwWdxFNp4Jbbo9N6CvZcl04SBR2XKewlUdBJss3+RcAP0H4Ebrk8Dfdd
      prDnoqCTeCoN3HJ7dFpPwZ7r0kmioOMyhb0kCjpJttm/CPgB2o/ALZen4b7LFPZcFHQST6WBW26P
      Tusp2HNdOkkUdFymsJdEQSfJNvsXAT9A+xG45fI03HeZwp6Lgk7iqTRwy+3RaT0Fe65LJ4mCjssU
      9pIo6CTZZv8i4AdoPwK3XJ6G+y5T2HNR0Ek8lQZuuT06radgz3XpJFHQcZnCXhIFnSTb7F8E/AAn
      MoU9FwWdN71pprD3Zhq41e49DZ/txPNx392g47LN/kXAD3AiU9hzUdB505tmCntvpoFb7d7T8NlO
      PB/33Q06LtvsXwT8ACcyhT0XBZ03vWmmsPdmGrjV7j0Nn+3E83Hf3aDjss3+RcAPcCJT2HNR0HnT
      m2YKe2+mgVvt3tPw2U48H/fdDTou2+xfBPwAJzKFPRcFnTe9aaaw92YauNXuPQ2f7cTzcd/doOOy
      zepFvmzywuy5Lh0XBR2XKex9tavSwK0TeyoKOs5TsOe6dNpMYS+Jgo7zTrJ6kS+bvDB7rkvHRUHH
      ZQp7X+2qNHDrxJ6Kgo7zFOy5Lp02U9hLoqDjvJOsXuTLJi/MnuvScVHQcZnC3le7Kg3cOrGnoqDj
      PAV7rkunzRT2kijoOO8kqxf5sskLs+e6dFwUdFymsPfVrkoDt07sqSjoOE/BnuvSaTOFvSQKOs47
      yepFvmzywuy5Lh0XBR2XKex9tavSwK0TeyoKOs5TsOe6dNpMYS+Jgo7zTrJ/cQA/iouCjvOmcCuJ
      go7zFOx9NQo6zlOw57p0nNfA/a0bKgo6Lr/KTz4ZP56Lgo7zpnAriYKO8xTsfTUKOs5TsOe6dJzX
      wP2tGyoKOi6/yk8+GT+ei4KO86ZwK4mCjvMU7H01CjrOU7DnunSc18D9rRsqCjouv8pPPhk/nouC
      jvOmcCuJgo7zFOx9NQo6zlOw57p0nNfA/a0bKgo6Lr/KTz4ZP56Lgo7zpnAriYKO8xTsfTUKOs5T
      sOe6dJzXwP2tGyoKOi6/yutPxg/VfixuuSjoOK+B++4GnTYKOq2nYC/pNvCmu0vHRUGnjYKOi4KO
      8xTsuWyzfxHwA7QfgVsuCjrOa+C+u0GnjYJO6ynYS7oNvOnu0nFR0GmjoOOioOM8BXsu2+xfBPwA
      7UfglouCjvMauO9u0GmjoNN6CvaSbgNvurt0XBR02ijouCjoOE/Bnss2+xcBP0D7EbjloqDjvAbu
      uxt02ijotJ6CvaTbwJvuLh0XBZ02CjouCjrOU7Dnss3+RcAP0H4Ebrko6DivgfvuBp02Cjqtp2Av
      6TbwprtLx0VBp42CjouCjvMU7Llss38R8AMk+SX4bO756DhPwZ7r0kkyhT3XpeOioOMyhb0TXTou
      CjrOU7CXdBXcavee4vWn4EdJ8kvw2dzz0XGegj3XpZNkCnuuS8dFQcdlCnsnunRcFHScp2Av6Sq4
      1e49xetPwY+S5Jfgs7nno+M8BXuuSyfJFPZcl46Lgo7LFPZOdOm4KOg4T8Fe0lVwq917itefgh8l
      yS/BZ3PPR8d5CvZcl06SKey5Lh0XBR2XKeyd6NJxUdBxnoK9pKvgVrv3FK8/BT9Kkl+Cz+aej47z
      FOy5Lp0kU9hzXTouCjouU9g70aXjoqDjPAV7SVfBrXbvKVafgh8gSQO3XBR0XBR0XKaw57p0TnhP
      Zwp7SRq45TKFvS/kF1h9Cn6AJA3cclHQcVHQcZnCnuvSOeE9nSnsJWnglssU9r6QX2D1KfgBkjRw
      y0VBx0VBx2UKe65L54T3dKawl6SBWy5T2PtCfoHVp+AHSNLALRcFHRcFHZcp7LkunRPe05nCXpIG
      brlMYe8L+QVWn4IfIEkDt1wUdFwUdFymsOe6dE54T2cKe0kauOUyhb0v5Bf4jaf4EfgHSv5I7Lko
      6Lgo6DivgfvtDW4le+y5PA33kyjouDRwy+3Rcd4v8LtP9gL8oyV/OPZcFHRcFHSc18D99ga3kj32
      XJ6G+0kUdFwauOX26DjvF/jdJ3sB/tGSPxx7Lgo6Lgo6zmvgfnuDW8keey5Pw/0kCjouDdxye3Sc
      9wv87pO9AP9oyR+OPRcFHRcFHec1cL+9wa1kjz2Xp+F+EgUdlwZuuT06zvsFfvfJXoB/tOQPx56L
      go6Lgo7zGrjf3uBWsseey9NwP4mCjksDt9weHef9AqtPxo/yZhR0nKdg780o6LRR0Gk9BXuuS+dE
      prCXREHnhDfNNqsX+bJvRkHHeQr23oyCThsFndZTsOe6dE5kCntJFHROeNNss3qRL/tmFHScp2Dv
      zSjotFHQaT0Fe65L50SmsJdEQeeEN802qxf5sm9GQcd5CvbejIJOGwWd1lOw57p0TmQKe0kUdE54
      02yzepEv+2YUdJynYO/NKOi0UdBpPQV7rkvnRKawl0RB54Q3zTarF/myWy/Mm8ld9too6Lg0cMtF
      Qcd5U7jl9uicyBT2XJeO8xTsJV0Ft5I99pLuSVafgh9g6yPwZnKXvTYKOi4N3HJR0HHeFG65PTon
      MoU916XjPAV7SVfBrWSPvaR7ktWn4AfY+gi8mdxlr42CjksDt1wUdJw3hVtuj86JTGHPdek4T8Fe
      0lVwK9ljL+meZPUp+AG2PgJvJnfZa6Og49LALRcFHedN4Zbbo3MiU9hzXTrOU7CXdBXcSvbYS7on
      WX0KfoCtj8CbyV322ijouDRwy0VBx3lTuOX26JzIFPZcl47zFOwlXQW3kj32ku5JVp+CH8B9BDpJ
      FHROeE9nCnuuS8d5CvZO5Gm4397glouCzheioOO8k6xe5Mu6F6aTREHnhPd0prDnunScp2DvRJ6G
      ++0Nbrko6HwhCjrOO8nqRb6se2E6SRR0TnhPZwp7rkvHeQr2TuRpuN/e4JaLgs4XoqDjvJOsXuTL
      uhemk0RB54T3dKaw57p0nKdg70SehvvtDW65KOh8IQo6zjvJ6kW+rHthOkkUdE54T2cKe65Lx3kK
      9k7kabjf3uCWi4LOF6Kg47yTrF7ky7oXppNEQSfxplHQcZ6CvS90FdxK9thro6CTeNNMYc9FQcdF
      QSfJNqsX+bLuhekkUdBJvGkUdJynYO8LXQW3kj322ijoJN40U9hzUdBxUdBJss3qRb6se2E6SRR0
      Em8aBR3nKdj7QlfBrWSPvTYKOok3zRT2XBR0XBR0kmyzepEv616YThIFncSbRkHHeQr2vtBVcCvZ
      Y6+Ngk7iTTOFPRcFHRcFnSTbrF7ky7oXppNEQSfxplHQcZ6CvS90FdxK9thro6CTeNNMYc9FQcdF
      QSfJNqsX+bLuhekkUdBJPBUFnTZT2HNdOs5TsOe6dFwUdE54Kgo6SRR0nNfAfXeDjsuvsvpk/Cju
      w9BJoqCTeCoKOm2msOe6dJynYM916bgo6JzwVBR0kijoOK+B++4GHZdfZfXJ+FHch6GTREEn8VQU
      dNpMYc916ThPwZ7r0nFR0DnhqSjoJFHQcV4D990NOi6/yuqT8aO4D0MniYJO4qko6LSZwp7r0nGe
      gj3XpeOioHPCU1HQSaKg47wG7rsbdFx+ldUn40dxH4ZOEgWdxFNR0GkzhT3XpeM8BXuuS8dFQeeE
      p6Kgk0RBx3kN3Hc36Lj8KqtPxo+y9WF4092ls+Up2HNdOi5T2HNR0HFR0GmjoOOioNN6U7jlsgFv
      bt39J6sX+bJbL8yb7i6dLU/BnuvScZnCnouCjouCThsFHRcFndabwi2XDXhz6+4/Wb3Il916Yd50
      d+lseQr2XJeOyxT2XBR0XBR02ijouCjotN4UbrlswJtbd//J6kW+7NYL86a7S2fLU7DnunRcprDn
      oqDjoqDTRkHHRUGn9aZwy2UD3ty6+09WL/Jlt16YN91dOluegj3XpeMyhT0XBR0XBZ02CjouCjqt
      N4VbLhvw5tbdf7J6kS/7ZhR0XBq4leyx57p0Wk/BnouCjvMauO9u0HFR0HFR0HGZwt5Wtlm9yJd9
      Mwo6Lg3cSvbYc106radgz0VBx3kN3Hc36Lgo6Lgo6LhMYW8r26xe5Mu+GQUdlwZuJXvsuS6d1lOw
      56Kg47wG7rsbdFwUdFwUdFymsLeVbVYv8mXfjIKOSwO3kj32XJdO6ynYc1HQcV4D990NOi4KOi4K
      Oi5T2NvKNqsX+bJvRkHHpYFbyR57rkun9RTsuSjoOK+B++4GHRcFHRcFHZcp7G1lm/2Ll8vl8pfc
      H6zL5fIZ7g/W5XL5DPcH63K5fIb7g3W5XD7D/cG6XC6f4f5gXS6Xz3B/sC6Xy2e4P1iXy+Uz3B+s
      y+XyGe4P1uVy+Qz3B+tyuXyG+4N1uVw+w/3Bulwun+H+YF0ul89wf7Aul8tnuD9Yl8vlM9wfrMvl
      8hnuD9blcvkM9wfrcrl8hvuDdblcPsP9wbpcLp/h/mBdLpfPcH+wLpfLZ7g/WJfL5TPcH6zL5fIZ
      7g/W5XL5DPcH63K5fIb/D09VzBXLmZkJAAAAAElFTkSuQmCC
      " target="_blank" style="cursor:pointer"><img src="/QIS/images/qr_code.svg" width="20" name=
      "qrCode" showID="detailPage" titleText="Für diese angegebene URL oder die aktuelle Seite." ti
      tle="Aktivieren Sie bitte JavaScript, um den QR-Code sehen zu können, oder klicken Sie auf
       diese
      s Icon!" /></a>
      <div id="detailPage" class="QRCodeTooltip" name="qrCodeDiv"><img src="data:image/png;base64,
      iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAo40lEQVR4Xu2Uwa7lSLIj+/9/emaR
      m2oDiedMKlxH1WEANwkjXdJNnP/8v8vlcvkI/+E/XC6Xy69yf7Aul8tnuD9Yl8vlM9wfrMvl8hnu
      D9blcvkM9wfrcrl8hvuDdblcPsP9wbpcLp/h/mBdLpfPcH+wLpfLZ7g/WJfL5TPcH6zL5fIZ7g/W
      5XL5DPcH63K5fIb7g3W5XD7D/cG6XC6f4f5gXS6Xz3B/sC6Xy2e4P1iXy+Uz3B+sy+XyGe4P1uVy
      +Qz3B+tyuXyG+4N1uVw+w/3Bulwun+H+YF0ul89wf7Aul8tnWP3B+s9//vMzeRruJzfYc2ngVrs3
      hTfdXTqJN82vw+d1z0znzWyzepEv+2aehvvJDfZcGrjV7k3hTXeXTuJN8+vwed0z03kz26xe5Mu+
      mafhfnKDPZcGbrV7U3jT3aWTeNP8Onxe98x03sw2qxf5sm/mabif3GDPpYFb7d4U3nR36STeNL8O
      n9c9M503s83qRb7sm3ka7ic32HNp4Fa7N4U33V06iTfNr8Pndc9M581ss3qRL7v1wrzp7tI5kSns
      vdltoqDjvAbuuxt0kijotFHQcd7T8ObW3X+yepEvu/XCvOnu0jmRKey92W2ioOO8Bu67G3SSKOi0
      UdBx3tPw5tbdf7J6kS+79cK86e7SOZEp7L3ZbaKg47wG7rsbdJIo6LRR0HHe0/Dm1t1/snqRL7v1
      wrzp7tI5kSnsvdltoqDjvAbuuxt0kijotFHQcd7T8ObW3X+yepEvu/XCvOnu0jmRKey92W2ioOO8
      Bu67G3SSKOi0UdBx3tPw5tbdf7J6kS/rXphOEgUd5zVw392g47wp3GqjoHMiCjpveioN3HJR0Em8
      aRR0nHeS1Yt8WffCdJIo6DivgfvuBh3nTeFWGwWdE1HQedNTaeCWi4JO4k2joOO8k6xe5Mu6F6aT
      REHHeQ3cdzfoOG8Kt9oo6JyIgs6bnkoDt1wUdBJvGgUd551k9SJf1r0wnSQKOs5r4L67Qcd5U7jV
      RkHnRBR03vRUGrjloqCTeNMo6DjvJKsX+bLuhekkUdBxXgP33Q06zpvCrTYKOieioPOmp9LALRcF
      ncSbRkHHeSdZvciXdS9MJ4mCTusp2Eu6Cm4le+y1XRUFHRcFHedN4Vayx57r0nFR0HGegj3XpZNE
      Qcd5J1m9yJd1L0wniYJO6ynYS7oKbiV77LVdFQUdFwUd503hVrLHnuvScVHQcZ6CPdelk0RBx3kn
      Wb3Il3UvTCeJgk7rKdhLugpuJXvstV0VBR0XBR3nTeFWssee69JxUdBxnoI916WTREHHeSdZvciX
      dS9MJ4mCTusp2Eu6Cm4le+y1XRUFHRcFHedN4Vayx57r0nFR0HGegj3XpZNEQcd5J1m9yJd1L0wn
      iYJO6ynYS7oKbiV77LVdFQUdFwUd503hVrLHnuvScVHQcZ6CPdelk0RBx3knWb3Il3UvTCeJgo7z
      FOwlUdBxnoK9E1HQOREFnTYN3HJ7dJzXwH13g04SBR3nnWT1Il/WvTCdJAo6zlOwl0RBx3kK9k5E
      QedEFHTaNHDL7dFxXgP33Q06SRR0nHeS1Yt8WffCdJIo6DhPwV4SBR3nKdg7EQWdE1HQadPALbdH
      x3kN3Hc36CRR0HHeSVYv8mXdC9NJoqDjPAV7SRR0nKdg70QUdE5EQadNA7fcHh3nNXDf3aCTREHH
      eSdZvciXdS9MJ4mCjvMU7CVR0HGegr0TUdA5EQWdNg3ccnt0nNfAfXeDThIFHeedZPUiX3brhXnT
      3aXjvAbuuxt0XBq45fboOG8Kt1wauJXssee6dJI0cKvdm8KbW3f/yepFvuzWC/Omu0vHeQ3cdzfo
      uDRwy+3Rcd4Ubrk0cCvZY8916SRp4Fa7N4U3t+7+k9WLfNmtF+ZNd5eO8xq4727QcWngltuj47wp
      3HJp4Fayx57r0knSwK12bwpvbt39J6sX+bJbL8yb7i4d5zVw392g49LALbdHx3lTuOXSwK1kjz3X
      pZOkgVvt3hTe3Lr7T1Yv8mW3Xpg33V06zmvgvrtBx6WBW26PjvOmcMulgVvJHnuuSydJA7favSm8
      uXX3n6xe5Mu+GQWd6/2BzvX+QOdN761ss3qRL/tmFHSu9wc61/sDnTe9t7LN6kW+7JtR0LneH+hc
      7w903vTeyjarF/myb0ZB53p/oHO9P9B503sr26xe5Mu+GQWd6/2BzvX+QOdN761ss3/xY/AP5P5I
      dJynYM916byZBm65PTqJN83TcL/N5b+5X+T/gP+B3H8iOs5TsOe6dN5MA7fcHp3Em+ZpuN/m8t/c
      L/J/wP9A7j8RHecp2HNdOm+mgVtuj07iTfM03G9z+W/uF/k/4H8g95+IjvMU7LkunTfTwC23Ryfx
      pnka7re5/Df3i/wf8D+Q+09Ex3kK9lyXzptp4Jbbo5N40zwN99tc/pvVL8I/xoko6LRR0Ekyhb0k
      Cjpv5mm4727QaaOg00ZBZ8vbZvUp+AFOREGnjYJOkinsJVHQeTNPw313g04bBZ02Cjpb3jarT8EP
      cCIKOm0UdJJMYS+Jgs6beRruuxt02ijotFHQ2fK2WX0KfoATUdBpo6CTZAp7SRR03szTcN/doNNG
      QaeNgs6Wt83qU/ADnIiCThsFnSRT2EuioPNmnob77gadNgo6bRR0trxtVp+CHyD5COwl3SncbzOF
      PRcFnRPe05nC3olMYS9JA7dcprDnunSct83qU/ADJB+BvaQ7hfttprDnoqBzwns6U9g7kSnsJWng
      lssU9lyXjvO2WX0KfoDkI7CXdKdwv80U9lwUdE54T2cKeycyhb0kDdxymcKe69Jx3jarT8EPkHwE
      9pLuFO63mcKei4LOCe/pTGHvRKawl6SBWy5T2HNdOs7bZvUp+AGSj8Be0p3C/TZT2HNR0DnhPZ0p
      7J3IFPaSNHDLZQp7rkvHedusPgU/wIko6LSegr02U9jb6iq45fbouExhr+2qNHDL7dFxaeCW26Pj
      ss3qRb7siSjotJ6CvTZT2NvqKrjl9ui4TGGv7ao0cMvt0XFp4Jbbo+OyzepFvuyJKOi0noK9NlPY
      2+oquOX26LhMYa/tqjRwy+3RcWngltuj47LN6kW+7Iko6LSegr02U9jb6iq45fbouExhr+2qNHDL
      7dFxaeCW26Pjss3qRb7siSjotJ6CvTZT2NvqKrjl9ui4TGGv7ao0cMvt0XFp4Jbbo+OyzepFvqx7
      YTrOexreTO6yt9X9N8Nv4qKgk0RBx3kN3G9vcCvZY89lm9WLfFn3wnSc9zS8mdxlb6v7b4bfxEVB
      J4mCjvMauN/e4Fayx57LNqsX+bLuhek472l4M7nL3lb33wy/iYuCThIFHec1cL+9wa1kjz2XbVYv
      8mXdC9Nx3tPwZnKXva3uvxl+ExcFnSQKOs5r4H57g1vJHnsu26xe5Mu6F6bjvKfhzeQue1vdfzP8
      Ji4KOkkUdJzXwP32BreSPfZctlm9yJdNoqCTeBtR0HGZwp7r0km8p/M03HeZwt6bUdBxmcKeyy+w
      +hT8AEkUdBJvIwo6LlPYc106ifd0nob7LlPYezMKOi5T2HP5BVafgh8giYJO4m1EQcdlCnuuSyfx
      ns7TcN9lCntvRkHHZQp7Lr/A6lPwAyRR0Em8jSjouExhz3XpJN7TeRruu0xh780o6LhMYc/lF1h9
      Cn6AJAo6ibcRBR2XKey5Lp3EezpPw32XKey9GQUdlynsufwCq0/BD+A+Ap0kU9hzeQs+R/Is7J3o
      0knSwC2XDXjTpYFbLgo6zlOwl3RPsvoU/ADuI9BJMoU9l7fgcyTPwt6JLp0kDdxy2YA3XRq45aKg
      4zwFe0n3JKtPwQ/gPgKdJFPYc3kLPkfyLOyd6NJJ0sAtlw1406WBWy4KOs5TsJd0T7L6FPwA7iPQ
      STKFPZe34HMkz8LeiS6dJA3cctmAN10auOWioOM8BXtJ9ySrT8EP4D4CnSRT2HN5Cz5H8izsnejS
      SdLALZcNeNOlgVsuCjrOU7CXdE+y+hT8AMlHYM916SSZwl7bVWnglksDt5I99pLuBny2E3ka7rso
      6CTZZvUiXzZ5YfZcl06SKey1XZUGbrk0cCvZYy/pbsBnO5Gn4b6Lgk6SbVYv8mWTF2bPdekkmcJe
      21Vp4JZLA7eSPfaS7gZ8thN5Gu67KOgk2Wb1Il82eWH2XJdOkinstV2VBm65NHAr2WMv6W7AZzuR
      p+G+i4JOkm1WL/Jlkxdmz3XpJJnCXttVaeCWSwO3kj32ku4GfLYTeRruuyjoJNlm9SJf1mUKey4N
      3Nrao9N6U7iV7LHnunQSr8kU9lyXjouCTuI1aeBWu/c3rF7ky7pMYc+lgVtbe3Rabwq3kj32XJdO
      4jWZwp7r0nFR0Em8Jg3cavf+htWLfFmXKey5NHBra49O603hVrLHnuvSSbwmU9hzXTouCjqJ16SB
      W+3e37B6kS/rMoU9lwZube3Rab0p3Er22HNdOonXZAp7rkvHRUEn8Zo0cKvd+xtWL/JlXaaw59LA
      ra09Oq03hVvJHnuuSyfxmkxhz3XpuCjoJF6TBm61e3/D6kW+rHthOs6bwq0kCjptprCXREHHeQr2
      XJeO8xq47zKFvSQKOltR0GmzzepFvqx7YTrOm8KtJAo6baawl0RBx3kK9lyXjvMauO8yhb0kCjpb
      UdBps83qRb6se2E6zpvCrSQKOm2msJdEQcd5CvZcl47zGrjvMoW9JAo6W1HQabPN6kW+rHthOs6b
      wq0kCjptprCXREHHeQr2XJeO8xq47zKFvSQKOltR0GmzzepFvqx7YTrOm8KtJAo6baawl0RBx3kK
      9lyXjvMauO8yhb0kCjpbUdBps83qRb5sEgUd5zVwf+uGSgO3kj32TnTptJnCXtJVcOvEnoqCjouC
      jvO2WX0KfoAkCjrOa+D+1g2VBm4le+yd6NJpM4W9pKvg1ok9FQUdFwUd522z+hT8AEkUdJzXwP2t
      GyoN3Er22DvRpdNmCntJV8GtE3sqCjouCjrO22b1KfgBkijoOK+B+1s3VBq4leyxd6JLp80U9pKu
      glsn9lQUdFwUdJy3zepT8AMkUdBxXgP3t26oNHAr2WPvRJdOmynsJV0Ft07sqSjouCjoOG+b1afg
      B3BR0HFR0HGegr2tbgNvuijotJ6CPdel47wp3EqioOO8KdxK9tg70aXjvJOsXuTLuijouCjoOE/B
      3la3gTddFHRaT8Ge69Jx3hRuJVHQcd4UbiV77J3o0nHeSVYv8mVdFHRcFHScp2Bvq9vAmy4KOq2n
      YM916ThvCreSKOg4bwq3kj32TnTpOO8kqxf5si4KOi4KOs5TsLfVbeBNFwWd1lOw57p0nDeFW0kU
      dJw3hVvJHnsnunScd5LVi3xZFwUdFwUd5ynY2+o28KaLgk7rKdhzXTrOm8KtJAo6zpvCrWSPvRNd
      Os47yepFvqx7YTqt9zS8mdxlL+kquJVkA950UdBxnoI9l7fgc5x4Fu67TGEv6T7F6kW+rHthOq33
      NLyZ3GUv6Sq4lWQD3nRR0HGegj2Xt+BznHgW7rtMYS/pPsXqRb6se2E6rfc0vJncZS/pKriVZAPe
      dFHQcZ6CPZe34HOceBbuu0xhL+k+xepFvqx7YTqt9zS8mdxlL+kquJVkA950UdBxnoI9l7fgc5x4
      Fu67TGEv6T7F6kW+rHthOq33NLyZ3GUv6Sq4lWQD3nRR0HGegj2Xt+BznHgW7rtMYS/pPsXqRb7s
      /2KmsPdmt8nTcD+Jgk7iNVHQab0p3HL5BVafgh/gfzFT2Huz2+RpuJ9EQSfxmijotN4Ubrn8AqtP
      wQ/wv5gp7L3ZbfI03E+ioJN4TRR0Wm8Kt1x+gdWn4Af4X8wU9t7sNnka7idR0Em8Jgo6rTeFWy6/
      wOpT8AP8L2YKe292mzwN95Mo6CReEwWd1pvCLZdfYPUp+AGSj8Ce69JxnoK9JFPYa7tPR0HHeQr2
      XJdO4qko6DivgfvtDW65KOg4T8Fe0j3J6lPwAyQfgT3XpeM8BXtJprDXdp+Ogo7zFOy5Lp3EU1HQ
      cV4D99sb3HJR0HGegr2ke5LVp+AHSD4Ce65Lx3kK9pJMYa/tPh0FHecp2HNdOomnoqDjvAbutze4
      5aKg4zwFe0n3JKtPwQ+QfAT2XJeO8xTsJZnCXtt9Ogo6zlOw57p0Ek9FQcd5Ddxvb3DLRUHHeQr2
      ku5JVp+CHyD5COy5Lh3nKdhLMoW9tvt0FHScp2DPdekknoqCjvMauN/e4JaLgo7zFOwl3ZOsPgU/
      gIuCzs2fNHDL7dE5kSnsJV0Ft1wUdE54T2cKey7brF7ky7oo6Nz8SQO33B6dE5nCXtJVcMtFQeeE
      93SmsOeyzepFvqyLgs7NnzRwy+3ROZEp7CVdBbdcFHROeE9nCnsu26xe5Mu6KOjc/EkDt9wenROZ
      wl7SVXDLRUHnhPd0prDnss3qRb6si4LOzZ80cMvt0TmRKewlXQW3XBR0TnhPZwp7LtvsXwT8AG0a
      uJVEQSeJgk7iPZ0GbiVp4Fa7p+B+coO9pKvg1q/t/Q37FwE/QJsGbiVR0EmioJN4T6eBW0kauNXu
      Kbif3GAv6Sq49Wt7f8P+RcAP0KaBW0kUdJIo6CTe02ngVpIGbrV7Cu4nN9hLugpu/dre37B/EfAD
      tGngVhIFnSQKOon3dBq4laSBW+2egvvJDfaSroJbv7b3N+xfBPwAbRq4lURBJ4mCTuI9nQZuJWng
      Vrun4H5yg72kq+DWr+39DasX+bIuCjouCjqJpzKFPZcp7J2Igs6Wp2AviYJOGwWdN72ns83qRb6s
      i4KOi4JO4qlMYc9lCnsnoqCz5SnYS6Kg00ZB503v6WyzepEv66Kg46Kgk3gqU9hzmcLeiSjobHkK
      9pIo6LRR0HnTezrbrF7ky7oo6Lgo6CSeyhT2XKawdyIKOluegr0kCjptFHTe9J7ONqsX+bIuCjou
      CjqJpzKFPZcp7J2Igs6Wp2AviYJOGwWdN72ns83qRb5sEgUd503hlssU9lyXjksDt5I99pKuglvJ
      HnttprCXZAp7SVfBrSS/yuqT8aMkUdBx3hRuuUxhz3XpuDRwK9ljL+kquJXssddmCntJprCXdBXc
      SvKrrD4ZP0oSBR3nTeGWyxT2XJeOSwO3kj32kq6CW8kee22msJdkCntJV8GtJL/K6pPxoyRR0HHe
      FG65TGHPdem4NHAr2WMv6Sq4leyx12YKe0mmsJd0FdxK8qusPhk/ShIFHedN4ZbLFPZcl45LA7eS
      PfaSroJbyR57baawl2QKe0lXwa0kv8rqk/GjuA9DJ/GejoLOiSjouDRw680o6DivgftJFHT+Tdlm
      9SJf1r0wncR7Ogo6J6Kg49LArTejoOO8Bu4nUdD5N2Wb1Yt8WffCdBLv6SjonIiCjksDt96Mgo7z
      GrifREHn35RtVi/yZd0L00m8p6OgcyIKOi4N3HozCjrOa+B+EgWdf1O2Wb3Il3UvTCfxno6Czoko
      6Lg0cOvNKOg4r4H7SRR0/k3ZZvUiX7bNBrzpoqCTeCob8Ka7S6eNgk7iNVHQOeFNo6DTegr2ku5T
      rF7ky7bZgDddFHQST2UD3nR36bRR0Em8Jgo6J7xpFHRaT8Fe0n2K1Yt82TYb8KaLgk7iqWzAm+4u
      nTYKOonXREHnhDeNgk7rKdhLuk+xepEv22YD3nRR0Ek8lQ14092l00ZBJ/GaKOic8KZR0Gk9BXtJ
      9ylWL/Jl22zAmy4KOomnsgFvurt02ijoJF4TBZ0T3jQKOq2nYC/pPsX+RcAP4KKgk3gqU9hzUdBx
      mcKe69JJPBUFnSRT2HNdOs6bwq0kCjrOU7DnunTa/AKvPwU/iouCTuKpTGHPRUHHZQp7rksn8VQU
      dJJMYc916ThvCreSKOg4T8Ge69Jp8wu8/hT8KC4KOomnMoU9FwUdlynsuS6dxFNR0EkyhT3XpeO8
      KdxKoqDjPAV7rkunzS/w+lPwo7go6CSeyhT2XBR0XKaw57p0Ek9FQSfJFPZcl47zpnAriYKO8xTs
      uS6dNr/A60/Bj+KioJN4KlPYc1HQcZnCnuvSSTwVBZ0kU9hzXTrOm8KtJAo6zlOw57p02vwCv/EU
      A/jx3Aek4zwFe65Lx3kN3E9usNd2VRR0Wk/BXpIGbrk9Oq33NLzp7tJx3ja/8RQD+PHcB6TjPAV7
      rkvHeQ3cT26w13ZVFHRaT8FekgZuuT06rfc0vOnu0nHeNr/xFAP48dwHpOM8BXuuS8d5DdxPbrDX
      dlUUdFpPwV6SBm65PTqt9zS86e7Scd42v/EUA/jx3Aek4zwFe65Lx3kN3E9usNd2VRR0Wk/BXpIG
      brk9Oq33NLzp7tJx3ja/8RQD+PHcB6TjPAV7rkvHeQ3cT26w13ZVFHRaT8FekgZuuT06rfc0vOnu
      0nHeNqtPwQ/QZgp7rkvHeVO45bIBb7Z3ueX26LTeFG4le+y5KOi4TGHv17LN6kW+bJsp7LkuHedN
      4ZbLBrzZ3uWW26PTelO4leyx56Kg4zKFvV/LNqsX+bJtprDnunScN4VbLhvwZnuXW26PTutN4Vay
      x56Lgo7LFPZ+LdusXuTLtpnCnuvScd4UbrlswJvtXW65PTqtN4VbyR57Lgo6LlPY+7Vss3qRL9tm
      CnuuS8d5U7jlsgFvtne55fbotN4UbiV77Lko6LhMYe/Xss3+xR+BH95FQcelgVtuj47LFPbaKOgk
      UdBp8zTc37qh0sCtdu9v2L/4I/DDuyjouDRwy+3RcZnCXhsFnSQKOm2ehvtbN1QauNXu/Q37F38E
      fngXBR2XBm65PTouU9hro6CTREGnzdNwf+uGSgO32r2/Yf/ij8AP76Kg49LALbdHx2UKe20UdJIo
      6LR5Gu5v3VBp4Fa79zfsX/wR+OFdFHRcGrjl9ui4TGGvjYJOEgWdNk/D/a0bKg3cavf+htWLfFkX
      BZ3EU5nCnssU9truRhR0Wu9peNPdpZN40yjotFHQcfkSq0/LD+WioJN4KlPYc5nCXtvdiIJO6z0N
      b7q7dBJvGgWdNgo6Ll9i9Wn5oVwUdBJPZQp7LlPYa7sbUdBpvafhTXeXTuJNo6DTRkHH5UusPi0/
      lIuCTuKpTGHPZQp7bXcjCjqt9zS86e7SSbxpFHTaKOi4fInVp+WHclHQSTyVKey5TGGv7W5EQaf1
      noY33V06iTeNgk4bBR2XL7H6tPxQLgo6Saawl3QV3GrTwC23R6fNFPZcFHRcGrjl9ugk3tOZwl7S
      3Wb1yfhRXBR0kkxhL+kquNWmgVtuj06bKey5KOi4NHDL7dFJvKczhb2ku83qk/GjuCjoJJnCXtJV
      cKtNA7fcHp02U9hzUdBxaeCW26OTeE9nCntJd5vVJ+NHcVHQSTKFvaSr4FabBm65PTptprDnoqDj
      0sAtt0cn8Z7OFPaS7jarT8aP4qKgk2QKe0lXwa02Ddxye3TaTGHPRUHHpYFbbo9O4j2dKewl3W1e
      fzJ+qPZjccvlabjvMoU9FwWdxFNp4Jbbo9N6CvZcl04SBR2XKewlUdBJss3+RcAP0H4Ebrk8Dfdd
      prDnoqCTeCoN3HJ7dFpPwZ7r0kmioOMyhb0kCjpJttm/CPgB2o/ALZen4b7LFPZcFHQST6WBW26P
      Tusp2HNdOkkUdFymsJdEQSfJNvsXAT9A+xG45fI03HeZwp6Lgk7iqTRwy+3RaT0Fe65LJ4mCjssU
      9pIo6CTZZv8i4AdoPwK3XJ6G+y5T2HNR0Ek8lQZuuT06radgz3XpJFHQcZnCXhIFnSTb7F8E/AAn
      MoU9FwWdN71pprD3Zhq41e49DZ/txPNx392g47LN/kXAD3AiU9hzUdB505tmCntvpoFb7d7T8NlO
      PB/33Q06LtvsXwT8ACcyhT0XBZ03vWmmsPdmGrjV7j0Nn+3E83Hf3aDjss3+RcAPcCJT2HNR0HnT
      m2YKe2+mgVvt3tPw2U48H/fdDTou2+xfBPwAJzKFPRcFnTe9aaaw92YauNXuPQ2f7cTzcd/doOOy
      zepFvmzywuy5Lh0XBR2XKex9tavSwK0TeyoKOs5TsOe6dNpMYS+Jgo7zTrJ6kS+bvDB7rkvHRUHH
      ZQp7X+2qNHDrxJ6Kgo7zFOy5Lp02U9hLoqDjvJOsXuTLJi/MnuvScVHQcZnC3le7Kg3cOrGnoqDj
      PAV7rkunzRT2kijoOO8kqxf5sskLs+e6dFwUdFymsPfVrkoDt07sqSjoOE/BnuvSaTOFvSQKOs47
      yepFvmzywuy5Lh0XBR2XKex9tavSwK0TeyoKOs5TsOe6dNpMYS+Jgo7zTrJ/cQA/iouCjvOmcCuJ
      go7zFOx9NQo6zlOw57p0nNfA/a0bKgo6Lr/KTz4ZP56Lgo7zpnAriYKO8xTsfTUKOs5TsOe6dJzX
      wP2tGyoKOi6/yk8+GT+ei4KO86ZwK4mCjvMU7H01CjrOU7DnunSc18D9rRsqCjouv8pPPhk/nouC
      jvOmcCuJgo7zFOx9NQo6zlOw57p0nNfA/a0bKgo6Lr/KTz4ZP56Lgo7zpnAriYKO8xTsfTUKOs5T
      sOe6dJzXwP2tGyoKOi6/yutPxg/VfixuuSjoOK+B++4GnTYKOq2nYC/pNvCmu0vHRUGnjYKOi4KO
      8xTsuWyzfxHwA7QfgVsuCjrOa+C+u0GnjYJO6ynYS7oNvOnu0nFR0GmjoOOioOM8BXsu2+xfBPwA
      7UfglouCjvMauO9u0GmjoNN6CvaSbgNvurt0XBR02ijouCjoOE/Bnss2+xcBP0D7EbjloqDjvAbu
      uxt02ijotJ6CvaTbwJvuLh0XBZ02CjouCjrOU7Dnss3+RcAP0H4Ebrko6DivgfvuBp02Cjqtp2Av
      6TbwprtLx0VBp42CjouCjvMU7Llss38R8AMk+SX4bO756DhPwZ7r0kkyhT3XpeOioOMyhb0TXTou
      CjrOU7CXdBXcavee4vWn4EdJ8kvw2dzz0XGegj3XpZNkCnuuS8dFQcdlCnsnunRcFHScp2Av6Sq4
      1e49xetPwY+S5Jfgs7nno+M8BXuuSyfJFPZcl46Lgo7LFPZOdOm4KOg4T8Fe0lVwq917itefgh8l
      yS/BZ3PPR8d5CvZcl06SKey5Lh0XBR2XKeyd6NJxUdBxnoK9pKvgVrv3FK8/BT9Kkl+Cz+aej47z
      FOy5Lp0kU9hzXTouCjouU9g70aXjoqDjPAV7SVfBrXbvKVafgh8gSQO3XBR0XBR0XKaw57p0TnhP
      Zwp7SRq45TKFvS/kF1h9Cn6AJA3cclHQcVHQcZnCnuvSOeE9nSnsJWnglssU9r6QX2D1KfgBkjRw
      y0VBx0VBx2UKe65L54T3dKawl6SBWy5T2PtCfoHVp+AHSNLALRcFHRcFHZcp7LkunRPe05nCXpIG
      brlMYe8L+QVWn4IfIEkDt1wUdFwUdFymsOe6dE54T2cKe0kauOUyhb0v5Bf4jaf4EfgHSv5I7Lko
      6Lgo6DivgfvtDW4le+y5PA33kyjouDRwy+3Rcd4v8LtP9gL8oyV/OPZcFHRcFHSc18D99ga3kj32
      XJ6G+0kUdFwauOX26DjvF/jdJ3sB/tGSPxx7Lgo6Lgo6zmvgfnuDW8keey5Pw/0kCjouDdxye3Sc
      9wv87pO9AP9oyR+OPRcFHRcFHec1cL+9wa1kjz2Xp+F+EgUdlwZuuT06zvsFfvfJXoB/tOQPx56L
      go6Lgo7zGrjf3uBWsseey9NwP4mCjksDt9weHef9AqtPxo/yZhR0nKdg780o6LRR0Gk9BXuuS+dE
      prCXREHnhDfNNqsX+bJvRkHHeQr23oyCThsFndZTsOe6dE5kCntJFHROeNNss3qRL/tmFHScp2Dv
      zSjotFHQaT0Fe65L50SmsJdEQeeEN802qxf5sm9GQcd5CvbejIJOGwWd1lOw57p0TmQKe0kUdE54
      02yzepEv+2YUdJynYO/NKOi0UdBpPQV7rkvnRKawl0RB54Q3zTarF/myWy/Mm8ld9too6Lg0cMtF
      Qcd5U7jl9uicyBT2XJeO8xTsJV0Ft5I99pLuSVafgh9g6yPwZnKXvTYKOi4N3HJR0HHeFG65PTon
      MoU916XjPAV7SVfBrWSPvaR7ktWn4AfY+gi8mdxlr42CjksDt1wUdJw3hVtuj86JTGHPdek4T8Fe
      0lVwK9ljL+meZPUp+AG2PgJvJnfZa6Og49LALRcFHedN4Zbbo3MiU9hzXTrOU7CXdBXcSvbYS7on
      WX0KfoCtj8CbyV322ijouDRwy0VBx3lTuOX26JzIFPZcl47zFOwlXQW3kj32ku5JVp+CH8B9BDpJ
      FHROeE9nCnuuS8d5CvZO5Gm4397glouCzheioOO8k6xe5Mu6F6aTREHnhPd0prDnunScp2DvRJ6G
      ++0Nbrko6HwhCjrOO8nqRb6se2E6SRR0TnhPZwp7rkvHeQr2TuRpuN/e4JaLgs4XoqDjvJOsXuTL
      uhemk0RB54T3dKaw57p0nKdg70SehvvtDW65KOh8IQo6zjvJ6kW+rHthOkkUdE54T2cKe65Lx3kK
      9k7kabjf3uCWi4LOF6Kg47yTrF7ky7oXppNEQSfxplHQcZ6CvS90FdxK9thro6CTeNNMYc9FQcdF
      QSfJNqsX+bLuhekkUdBJvGkUdJynYO8LXQW3kj322ijoJN40U9hzUdBxUdBJss3qRb6se2E6SRR0
      Em8aBR3nKdj7QlfBrWSPvTYKOok3zRT2XBR0XBR0kmyzepEv616YThIFncSbRkHHeQr2vtBVcCvZ
      Y6+Ngk7iTTOFPRcFHRcFnSTbrF7ky7oXppNEQSfxplHQcZ6CvS90FdxK9thro6CTeNNMYc9FQcdF
      QSfJNqsX+bLuhekkUdBJPBUFnTZT2HNdOs5TsOe6dFwUdE54Kgo6SRR0nNfAfXeDjsuvsvpk/Cju
      w9BJoqCTeCoKOm2msOe6dJynYM916bgo6JzwVBR0kijoOK+B++4GHZdfZfXJ+FHch6GTREEn8VQU
      dNpMYc916ThPwZ7r0nFR0DnhqSjoJFHQcV4D990NOi6/yuqT8aO4D0MniYJO4qko6LSZwp7r0nGe
      gj3XpeOioHPCU1HQSaKg47wG7rsbdFx+ldUn40dxH4ZOEgWdxFNR0GkzhT3XpeM8BXuuS8dFQeeE
      p6Kgk0RBx3kN3Hc36Lj8KqtPxo+y9WF4092ls+Up2HNdOi5T2HNR0HFR0GmjoOOioNN6U7jlsgFv
      bt39J6sX+bJbL8yb7i6dLU/BnuvScZnCnouCjouCThsFHRcFndabwi2XDXhz6+4/Wb3Il916Yd50
      d+lseQr2XJeOyxT2XBR0XBR02ijouCjotN4UbrlswJtbd//J6kW+7NYL86a7S2fLU7DnunRcprDn
      oqDjoqDTRkHHRUGn9aZwy2UD3ty6+09WL/Jlt16YN91dOluegj3XpeMyhT0XBR0XBZ02CjouCjqt
      N4VbLhvw5tbdf7J6kS/7ZhR0XBq4leyx57p0Wk/BnouCjvMauO9u0HFR0HFR0HGZwt5Wtlm9yJd9
      Mwo6Lg3cSvbYc106radgz0VBx3kN3Hc36Lgo6Lgo6LhMYW8r26xe5Mu+GQUdlwZuJXvsuS6d1lOw
      56Kg47wG7rsbdFwUdFwUdFymsLeVbVYv8mXfjIKOSwO3kj32XJdO6ynYc1HQcV4D990NOi4KOi4K
      Oi5T2NvKNqsX+bJvRkHHpYFbyR57rkun9RTsuSjoOK+B++4GHRcFHRcFHZcp7G1lm/2Ll8vl8pfc
      H6zL5fIZ7g/W5XL5DPcH63K5fIb7g3W5XD7D/cG6XC6f4f5gXS6Xz3B/sC6Xy2e4P1iXy+Uz3B+s
      y+XyGe4P1uVy+Qz3B+tyuXyG+4N1uVw+w/3Bulwun+H+YF0ul89wf7Aul8tnuD9Yl8vlM9wfrMvl
      8hnuD9blcvkM9wfrcrl8hvuDdblcPsP9wbpcLp/h/mBdLpfPcH+wLpfLZ7g/WJfL5TPcH6zL5fIZ
      7g/W5XL5DPcH63K5fIb/D09VzBXLmZkJAAAAAElFTkSuQmCC
      " /></div>
      Theoretische Informatik (früher: Grundlagen der Theoretischen Informatik) - Einzelansicht
      </h1>




      <div class="functionnavi">
      <ul>
      <li class="randlos">Funktionen:</li>
      <li class="randlos">
      <input class="submit" type="Submit" value="markierte Termine vormerken">
      </li>

      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=wwrite&amp;write=look&amp;
      par=old&amp;from=out&amp;addParallel=223554&amp;asi=">belegen/abmelden</a>

      \s
      \s
      \s
      \s
      \s
      \s



      \s


      \s
      </ul>
      </div>


      <a name="navigation"></a>
      <div class="mikronavi">
      <ul>
      <li class="randlos">Seiteninhalt:</li>


      \s
      <li class="randlos"><a class="regular" href="#basicdata" title="Springen zum Seitenabschnitt 
      Grunddaten">Grunddaten</a></li>

      <li><a class="regular" href="#terms" title="Springen zum Seitenabschnitt Termine">Termi
      ne</a></li>

      <li><a class="regular" href="#persons" title="Springen zum Seitenabschnitt Zugeordnete Pe
      rsonen">
      Zugeordnete Person</a></li>

      <li><a class="regular" href="#curricular" title="Springen zum Seitenabschnitt Studiengänge">
      Studiengänge</a></li>



      <li><a class="regular" href="#institutions" title="Springen zum Seitenabschnitt Einri
      chtungen">
      Einrichtungen</a></li>



      <li><a class="regular" href="#treeview" title="Springen zum Seitenabschnitt Struktur
      baum">
      Strukturbaum</a></li>
      </ul>
      </div>


      <div class="abstand_veranstaltung"></div>
      <a name="basicdata"></a>

      <table summary="Grunddaten zur Veranstaltung" border="0">
      <caption class="t_capt">Grunddaten</caption>
      <tr>
      <th class="mod" id="basic_1">Veranstaltungsart</th>
      <td class="mod_n_basic" headers="basic_1">Vorlesung/ Übung</td>


      <th class="mod" id="basic_2">Anz. Teilnehmer St.Universale</th>
      <td class="mod_n_basic" headers="basic_2"> </td>

      </tr>
      <tr>
      <th class="mod" id="basic_3">VeranstaltungsID</th>
      <td class="mod_n_basic" headers="basic_3">223554</td>


      <th class="mod" id="basic_2">Anzahl Credits Studium Universale</th>
      <td class="mod_n_basic" headers="basic_2"> </td>
      </tr>
      <tr>
      <th class="mod" id="basic_5">Semester</th>
      <td class="mod_n_basic" headers="basic_5">SoSe 2022</td>

      <th class="mod" id="basic_6">SWS</th>
      <td class="mod_n_basic" headers="basic_6"> </td>
      </tr>
      <tr>
      <th class="mod" id="basic_7">Erwartete Teilnehmer/-innen</th>
      <td class="mod_n_basic" headers="basic_7"> </td>

      <th class="mod" id="basic_8">Max. Teilnehmer/-innen</th>
      <td class="mod_n_basic" headers="basic_8"> </td>
      </tr>
      <tr>
      <th class="mod" id="basic_9">Rhythmus</th>
      <td class="mod_n_basic" headers="basic_9">2 jedes 2. Semester</td>

      <th class="mod" id="basic_10">Studienjahr</th>
      <td class="mod_n_basic" headers="basic_10"> </td>
      </tr>
      <tr>
      <th class="mod" id="basic_11">ECTS ohne Prüfung</th>
      <td class="mod_n_basic" headers="basic_11"> </td>

      <th class="mod" id="basic_11">ECTS mit Prüfung</th>
      <td class="mod_n_basic" headers="basic_11">10 ECTS für Vorlesung und Übung</td>


      </tr>
      <tr>
      <th class="mod" id="basic_13">Hyperlink</th>
      <td class="mod_n_basic" headers="basic_13">
      &nbsp;
      </td>



      <th class="mod" id="basic_11">QVM finanziert</th>
      <td class="mod_n_basic" headers="basic_11"> </td>

      </tr>


      <tr>
      <th class="mod" id="basic_16">Sprache</th>
      <td class="mod_n_basic" headers="basic_16">deutsch</td>
      </tr>

      <tr>
      <th class="mod" id="basic_17" rowspan="1">
      Belegungsfrist
      </th>
      <td class="mod_n_basic" headers="basic_17" colspan="3" >
      HHU Allgemeine Frist (ganzsemestrig, direkte Zul)
      &nbsp;&nbsp; 01.03.2022 - 14.09.2022 &nbsp;&nbsp;
      <span class="grueneWarnung">aktuell</span>
      </td>
      </tr>

      </table>





      <a name="terms"></a>



      \s


      <div class="abstand_veranstaltung"></div>
      <table summary="Übersicht über alle Veranstaltungstermine">
      <caption class="t_capt">
      Termine Gruppe: [unbenannt]
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=transform&amp;vm
      file=no&
      amp;veranstaltung.veranstid=223554&amp;veransttermin.parallelid=&amp;moduleCall=iCalend
      arGruppe&
      amp;publishConfFile=reports&amp;publishSubDir=veranstaltung" hreflang="de" charset="ISO
      -8859-1" 
      class="tree">
      <img class="regular" src="/QIS/images//calendar_go.svg" alt="iCalendar Export für Outlo
      ok" titl
      e="iCalendar Export für Outlook">
      </a>
      </caption>
      <tr>
      <th scope="col" class="mod">Tag</th>
      <th scope="col" class="mod">Zeit</th>
      <th scope="col" class="mod">Rhythmus</th>
      <th scope="col" class="mod">Dauer</th>
      <th scope="col" class="mod">Raum</th>
      <th scope="col" class="mod">Raum-<br>plan</th>
      <th scope="col" class="mod">Lehrperson</th>
      <th scope="col" class="mod">Status</th>
      <th scope="col" class="mod">Bemerkung</th>
      <th scope="col" class="mod">fällt aus am</th>
      <th scope="col" class="mod">Max. Teilnehmer/-innen</th>
      <th scope="col" class="mod">&nbsp;</th>
      </tr>

      <tr>
      <td class="mod_n_odd">
      Di.
      </td>
      <td class="mod_n_odd">
      08:30&nbsp;bis&nbsp;10:30  \s
      </td>
      <td class="mod_n_odd">
      woch
      </td>
      <td class="mod_n_odd">
      05.04.2022&nbsp;bis&nbsp;12.07.2022&nbsp;



      </td>

      <td class="mod_n_odd">
      <a class="regular" title="Details ansehen zu Raum 2321.HS 3H" href="https://lsf.hhu.de/qisserv
      er/rds?state=verpublish&amp;status=init&amp;vmfile=no&amp;moduleCall=webInfo&amp;publi
      shConfFil
      e=webInfoRaum&amp;publishSubDir=raum&amp;keep=y&amp;raum.rgid=3">0-Hörsaal - 2321.HS 3H</a>
      </td>
      <td class="mod_n_odd">
      </td>


      <td class="mod_n_odd">&nbsp;</td>

      <td class="mod_n_odd">&nbsp;</td>


      <td class="mod_n_odd">
      Vorlesung (4 SWS)
      </td>





      <td class="mod_n_odd">
      &nbsp;
      </td>
      <td class="mod_n_odd">
      \s
      </td>


      <td class="mod_n_odd">
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=init&amp;vmfile=no&amp;
      moduleCall=webInfo&amp;publishConfFile=webInfo&amp;publishSubDir=veranstaltung&amp;ve
      ranstaltung
      .veranstid=223554&amp;expand=543826#543826">
      <img src="/QIS/images//arrow_right_fat.svg" height="12" alt="Einzeltermine anzeigen" 
      title="Einzeltermine anzeigen">
      </a><br>
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=transform&amp;vmfile=
      n
      o&amp;publishid=543826&amp;moduleCall=iCalendar&amp;publishConfFile=reports&amp;publishSubD
      ir=veranstaltung" hreflang="de" charset="ISO-8859-1" class="tree">
      <img class="regular" src="/QIS/images//calendar_go.svg" alt="iCalendar Export für Outlook" 
      title="iCalendar Export für Outlook">
      </a>
      </td>



      </tr>

      <tr>
      <td class="mod_n_even">
      Fr.
      </td>
      <td class="mod_n_even">
      12:30&nbsp;bis&nbsp;14:30  \s
      </td>
      <td class="mod_n_even">
      woch
      </td>
      <td class="mod_n_even">
      08.04.2022&nbsp;bis&nbsp;15.07.2022&nbsp;



      </td>

      <td class="mod_n_even">
      <a class="regular" title="Details ansehen zu Raum 2521.HS 5F" href="https://lsf.hhu.de/qisserv
      er/rds?state=verpublish&amp;status=init&amp;vmfile=no&amp;moduleCall=webInfo&amp;publishConfF
      ile=webInfoRaum&amp;publishSubDir=raum&amp;keep=y&amp;raum.rgid=16">0-Hörsaal - 2521.HS 5F</a>
      </td>
      <td class="mod_n_even">
      </td>


      <td class="mod_n_even">&nbsp;</td>

      <td class="mod_n_even">&nbsp;</td>


      <td class="mod_n_even">
      Vorlesung (4 SWS)
      </td>





      <td class="mod_n_even">
      &nbsp;
      </td>
      <td class="mod_n_even">
      \s
      </td>


      <td class="mod_n_even">
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=init&amp;vmfile=no&amp;
      moduleCall=webInfo&amp;publishConfFile=webInfo&amp;publishSubDir=veranstaltung&amp;veranstalt
      ung.veranstid=223554&amp;expand=539201#539201">
      <img src="/QIS/images//arrow_right_fat.svg" height="12" alt="Einzeltermine anzeigen" title="E
      inzeltermine anzeigen">
      </a><br>
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=transform&amp;vmfile=no
      &amp;publishid=539201&amp;moduleCall=iCalendar&amp;publishConfFile=reports&amp;publishSubDir=
      veranstaltung" hreflang="de" charset="ISO-8859-1" class="tree">
      <img class="regular" src="/QIS/images//calendar_go.svg" alt="iCalendar Export für Outlook" t
      itle="iCalendar Export für Outlook">
      </a>
      </td>



      </tr>

      <tr>
      <td class="mod_n_odd">
      -.
      </td>
      <td class="mod_n_odd">
      &nbsp;bis&nbsp;   \s
      </td>
      <td class="mod_n_odd">
      woch
      </td>
      <td class="mod_n_odd">



      </td>

      <td class="mod_n_odd">
      &nbsp;
      </td>
      <td class="mod_n_odd">
      </td>


      <td class="mod_n_odd">&nbsp;</td>

      <td class="mod_n_odd">&nbsp;</td>


      <td class="mod_n_odd">
      Übungen (2 SWS) n. V.
      </td>





      <td class="mod_n_odd">
      &nbsp;
      </td>
      <td class="mod_n_odd">
      \s
      </td>


      <td class="mod_n_odd">
      <a href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status=transform&amp
      ;vmfile=no&amp;
      publishid=539200&amp;moduleCall=iCalendar&amp;publishConfFile=reports&amp;publishSub
      Dir=veranstaltu
      ng" hreflang="de" charset="ISO-8859-1" class="tree">
      <img class="regular" src="/QIS/images//calendar_go.svg" alt="iCalendar Export für Out
      look" title
      ="iCalendar Export für Outlook">
      </a>
      </td>



      </tr>
      </table>

      <div class="webTerm_activities">
      <div class="just_float_left">
      Gruppe [unbenannt]:
      </div>

      <div class="macro_div">
      <input id="BelegLinksTerminStg_1_" type="checkbox" name="add.223554" value="null">
      <label for="BelegLinksTerminStg_1_">vormerken</label>
      </div>
      <div class="macro_div">
      </div>  \s
      <div class="macro_div"> \s
      <img src="/QIS/images//arrow_right_fat.svg" alt=""> \s
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=wwrite&amp;write=lo
      ok&amp;from=o
      ut&amp;par=old&amp;add.223554=null&amp;asi=">jetzt belegen / abmelden</a>
      </div>  \s
      <div class="macro_div">
      </div> \s
      &nbsp;
      <input class="submit" type="Submit" value="markierte Termine vormerken">
      </div>

      <a name="persons"></a>
      <br />
      <br />


      <table summary="Verantwortliche Dozenten">
      <caption class="t_capt">Zugeordnete Person</caption>
      <tr>
      <th scope="col" class="mod" id="persons_1">
      Zugeordnete Person\s
      </th>
      <th scope="col" class="mod" id="persons_2">
      Zuständigkeit
      </th>

      </tr>
      <tr>
      <td class="mod_n_odd" headers="persons_1">

      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;statu
      s=init&amp;v
      mfile=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoPerson&amp;publishSubDir=p
      ersonal&am
      p;keep=y&amp;personal.pid=4174" title="Mehr Informationen">
      Rothe,&nbsp;Jörg-Matthias ,&nbsp;Univ.-Prof. Dr.</a>
      </td>
      <td class="mod_n_odd" headers="persons_2">


      </td>

      </tr>
      </table>


      <div class="abstand_veranstaltung"></div>
      <a name="curricular"></a>
      <table summary="Übersicht über die zugehörigen Studiengänge">
      <caption class="t_capt">Studiengänge</caption>
      <tr>
      <th scope="col" class="mod" id="curricular_1">Abschluss</th>
      <th scope="col" class="mod" id="curricular_2">Studiengang</th>
      <th scope="col" class="mod" id="curricular_3">Semester</th>
      <th scope="col" class="mod" id="curricular_4">PO-Version</th>
      <!-- <th scope="col" class="mod" id="curricular_4">Leistungspunkte</th>
      <th scope="col" class="mod" id="curricular_5">Bonuspunkte</th>
      <th scope="col" class="mod" id="curricular_6">ECTS</th> -->
      </tr>
      <tr>
      <td class="mod_n_odd" headers="curricular_1">Bachelor</td>
      <td class="mod_n_odd" headers="curricular_2">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;statu
      s=init&
      amp;vmfile=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoStg&amp;publishSubDi
      r=stg&amp;k_
      abstgv.abstgvnr=10204" title="Mehr Informationen">
      Informatik (BSc, PO 2013)
      </a>
      </td>
      <td class="mod_n_odd" headers="curricular_3">
      - \s
      </td>
      <td class="mod_n_odd" headers="curricular_4">
      2013
      </td>
      <!--
      <td class="mod_n_odd" headers="curricular_4">
      \s
      </td>
      <td class="mod_n_odd" headers="curricular_5">
      \s
      </td>
      <td class="mod_n_odd" headers="curricular_6">
      \s
      </td>
      -->
      </tr>
      <tr>
      <td class="mod_n_even" headers="curricular_1">Bachelor</td>
      <td class="mod_n_even" headers="curricular_2">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status
      =init&amp;
      vmfile=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoStg&amp;publishSubDir=stg
      &amp;k_abstgv
      .abstgvnr=10017" title="Mehr Informationen">
      Informatik (BSc, PO 2007)
      </a>
      </td>
      <td class="mod_n_even" headers="curricular_3">
      - \s
      </td>
      <td class="mod_n_even" headers="curricular_4">
      2007
      </td>
      <!--
      <td class="mod_n_even" headers="curricular_4">
      \s
      </td>
      <td class="mod_n_even" headers="curricular_5">
      \s
      </td>
      <td class="mod_n_even" headers="curricular_6">
      \s
      </td>
      -->
      </tr>
      <tr>
      <td class="mod_n_odd" headers="curricular_1">Bachelor</td>
      <td class="mod_n_odd" headers="curricular_2">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;statu
      s=init&amp;
      vmfile=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoStg&amp;publishSubDir=st
      g&amp;k_abstgv.
      abstgvnr=10312" title="Mehr Informationen">
      Informatik (BSc, PO 2016)
      </a>
      </td>
      <td class="mod_n_odd" headers="curricular_3">
      - \s
      </td>
      <td class="mod_n_odd" headers="curricular_4">
      2016
      </td>
      <!--
      <td class="mod_n_odd" headers="curricular_4">
      \s
      </td>
      <td class="mod_n_odd" headers="curricular_5">
      \s
      </td>
      <td class="mod_n_odd" headers="curricular_6">
      \s
      </td>
      -->
      </tr>
      <tr>
      <td class="mod_n_even" headers="curricular_1">Bachelor</td>
      <td class="mod_n_even" headers="curricular_2">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;status
      =init&amp;vm
      file=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoStg&amp;publishSubDir=
      stg&amp;k_abstgv.
      abstgvnr=10527" title="Mehr Informationen">
      Informatik (BSc, PO 2021)
      </a>
      </td>
      <td class="mod_n_even" headers="curricular_3">
      - \s
      </td>
      <td class="mod_n_even" headers="curricular_4">
      2021
      </td>
      <!--
      <td class="mod_n_even" headers="curricular_4">
      \s
      </td>
      <td class="mod_n_even" headers="curricular_5">
      \s
      </td>
      <td class="mod_n_even" headers="curricular_6">
      \s
      </td>
      -->
      </tr>
      </table>
      \s

      <div class="abstand_veranstaltung"></div>
      <a name="curricular"></a>
      <table summary="Übersicht über die zugehörigen Module">
      <caption class="t_capt">Module</caption>
      <tr>
      <th scope="col" class="mod" id="curricular_2">Modul</th>
      </tr>
      </table>
      <div class="abstand_veranstaltung"></div>
      <a name="institutions"></a>
      <table summary="Übersicht über die zugehörigen Einrichtungen" border="0">
      <caption class="t_capt">Zuordnung zu Einrichtungen</caption>

      <tr>
      <td class="mod_n_odd">
      <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=verpublish&amp;statu
      s=init&amp;
      vmfile=no&amp;moduleCall=webInfo&amp;publishConfFile=webInfoEinrichtung&amp;publishSubDir=e
      inrichtung&amp;einrichtung.eid=360" title="Mehr Informationen">
      Wissenschaftliche Einrichtung Informatik
      </a>
      </td>
      </tr>
      </table>





      <br />
      <a name="treeview"></a><div class="t_capt">Strukturbaum</div>

      Die Veranstaltung wurde <strong>1</strong> mal im Vorlesungsverzeichnis  SoSe 2022 gefunden:

      <div style="padding: 6px; line-height: 150%;">
      <div style="padding-left: 0px;">
      <img src="/QIS/images//spacer.svg" alt="">




      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;root120221=
      70088&amp;tre
      x=step" class="ueb">Lehrveranstaltungen Sommersemester 2022</a>
      </div>

      <div style="padding-left: 10px;">




      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;root120221=70088%7C6982
      3&amp;trex=step" class="ueb">Mathematisch-Naturwissenschaftliche Fakultät</a>
      </div>
      <div style="padding-left: 20px;">




      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;root120221=70088%7C698
      3%7C70479&amp;trex=step" class="ueb">Informatik</a>
      </div>
      <div style="padding-left: 30px;">




      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;root120221=70088%7C698
      23%7C70479%7C70596&amp;trex=step" class="ueb">Bachelor Informatik</a>
      </div>
      <div style="padding-left: 40px;">




      <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;root120221=70088%7C6982
      3%7C70479%7C70596%7C70554&amp;trex=step" class="ueb">Pflichtmodule der Informatik
       (1. - 4. Fachsemester Bachelor)</a>
      &nbsp;<span class="warnung">-&nbsp;-&nbsp;-&nbsp;1</span>
      </div>
      </div>
      </form>



      </div>
      <div style="clear: both;"></div>
      </div>
      \s
      <div style="padding-bottom: 7em;"></div>
      <div class="divfoot">
      <div class="divfoot_navigation">
      <a href="https://lsf.hhu.de/qisserver/rds?state=template&amp;template=about" 
      class="links3">Impressum und Datenschutz</a> |
      <a href="https://www.uni-duesseldorf.de/home/footer/datenschutz.html" 
      class="links3">Datenschutz</a>
      <div style="float: right; padding-right: 10px; line-height: 20px;">
      capuma-lsf-prod-as04</div>

      </div>
      <div class="divfoot_logo">QIS, LSF und HISinOne sind Produkte der\s
      <img src="/QIS/images//his_logoklein.gif" alt="Heinrich Heine Universität Düsseldorf" 
      border="0">
      eG
      </div>
      </div>


      <!-- Matomo -->
      <script type="text/javascript">
      var _paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
      var u="//piwik.rz.uni-duesseldorf.de/piwik/";
      _paq.push(['setTrackerUrl', u+'matomo.php']);
      _paq.push(['setSiteId', '58']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; 
      s.parentNode.insertBefore(g,s);
      })();
      </script>
      <!-- End Matomo Code -->
      </div>
      <script type="text/javascript" src="/qisserver/resources/bower_components/
      jquery/dist/jquery.min.js"></script>
      <script type="text/javascript" src="/qisserver/pub/js/qis-00000001.js"></script>
      <script type="text/javascript" src="/qisserver/pub/js/qrCode.js"></script>   

      <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver_functions.js"></script>
      <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver_language_init.js">
      </script>
      <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver.js"></script>

      <script src="/qisserver/pub//js/availability.js" type="text/javascript"></script>
      </body>
      </html>

      """;

  static String FALSCHE_PAGE = """
       
       <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/
       loose.dtd">\s
       <html lang="de">
       <head>
       <!-- Generated by node "capuma-lsf-prod-as04" in cluster "cl_p" using thread ajp-nio-192.168
       .164.244-8009-exec-1 -->
       <title>\s
       \s

      - :\s
       Heinrich Heine Universität Düsseldorf </title>
       <link rel="stylesheet" type="text/css" href="/qisserver/pub/QISDesign_HHU.css?1">




       <link rel="icon" href="/favicon.ico" type="image/gif">
       <link rel="top" href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=0&amp;topitem="
        title="Top">\s
       <link rel="stylesheet" type="text/css" media="print" href="/qisserver/pub/Print.css">
       <meta http-equiv="content-type" content="text/html; charset=UTF-8">
       <meta http-equiv="Cache-Control" content="private,must-revalidate,no-cache,no-store">
       </head>


       <body>


       <div id="wrapper">


       <div class="unsichtbar">


       <a accesskey="1" href="#navi">Zur Seitennavigation oder mit Tastenkombination für den <span
        lang="en">accesskey</span>-Taste und Taste 1</a>&nbsp;<br>
       <a accesskey="2" href="#lese">Zum Seiteninhalt oder mit Tastenkombination für den <span lan
       g="en">accesskey</span> und Taste 2</a>&nbsp;

       </div>
       <div class="header_hisinone">
       <div class="logo">
       <a href="https://lsf.hhu.de/qisserver/rds?state=redirect&amp;destination=http%3A%2F%2Fwww.h
       hu.de&amp;timestamp=1647515936421&amp;hash=0dc033df1ae1489ebc855bdc2202feca" target="_blank">
       <img src="/QIS/images//logo_rgb_HHU.jpg" height="104" alt="Heinrich Heine Universität 
       Düsseldorf"
        title="Heinrich Heine Universität Düsseldorf" border="0"></a>
       </div>



       <div class="services">
       <ol>
       <li>
       \s


       \s
       <a href="https://lsf.hhu.de/qisserver/rds?state=change&amp;type=6&amp;moduleParameter=semest
       erSelect&amp;nextdir=change&amp;next=SearchSelect.vm&amp;subdir=applications&amp;targettype=
       7&amp;targetstate=change&amp;getglobal=semester" id="choosesemester" title="Semester wähle
       n ...">
       SoSe 2022
       </a>
       <img src="/QIS/images//his_strich_blau.gif" width="1" height="11" alt="">
       </li>
       <li><a href="https://lsf.hhu.de/qisserver/rds?state=helpdoc&amp;calling=helpcenter&amp;topit
       em=leer&amp;breadCrumbSource=" title="Hilfe"> Hilfe</a> <img src="/QIS/images//his_strich_bl
       au.gif" width="1" height="11" alt=""></li>
       <li><a href="https://lsf.hhu.de/qisserver/rds?state=helpdoc&amp;calling=myhhuinfo&amp;topite
       m=leer&amp;breadCrumbSource=" title="Info"> Info</a> <img src="/QIS/images//his_strich_blau
       .gif" width="1" height="11" alt=""></li>

       <li>
       <a href="https://lsf.hhu.de/qisserver/rds?state=sitemap&amp;topitem=leer&amp;breadCrumbSourc
       e="  title="Sitemap">Sitemap</a>
       <img src="/QIS/images//his_strich_blau.gif" width="1" height="11" alt="">
       </li>

       </ol>

       \s
       <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=5&amp;language=en"><img SRC=
       "/QIS/images/flag_en.svg" alt="Switch to english language" vspace="2" height="16" width="16"
        style="vertical-align:text-top;" border="0" lang="en" title="Switch to english language">
        </a>
       \s
       </div><div style="clear:both;"></div>
       </div>





       <div class="divloginstatus">



       <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=0&amp;topitem=&amp;breadCrum
       bSource=&amp;topitem=functions" title="Startseite" class="links3"><u>S</u>tartseite</a>
       <span>
       &nbsp;<img src="/QIS/images//his_strich.gif" width="1" height="11" alt="">&nbsp;
       </span>
       <a href="https://lsf.hhu.de/qisserver/rds?state=wlogin&amp;login=in&amp;breadCrumbSource="
        class="links3" accesskey="l"><u>A</u>nmelden</a>
       <span>
       &nbsp;<img src="/QIS/images//his_strich.gif" width="1" height="11" alt="">&nbsp;
       </span>




       \s

       &nbsp;\s


       <div style="float:right;margin-right:5px; display:none;">
       <logout active="n" style="" class="" maxtime="30" timeoutmessage="Ihre Session-Zeit ist ab
       gelaufen. Bitte melden Sie sich wieder an um weiterzuarbeiten."\s
       class5min="" class10min="" minutetext_singular="Minute" minutetext_plural="Minuten" _show
       OnMin="10">
       <logouttext>Logout in <span class="boldMin" id="min">[min]</span> [minutetext]</logouttext>
       </logout>
       </div>

       </div>

       <div class="divlinks">
       <a name="navi"></a>


       <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=8&amp;topitem=lectures&a
       mp;breadCrumbSource="
       class="links2visited ">Veranstaltungen</a>


       &nbsp;&nbsp;&nbsp;&nbsp;


       <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=8&amp;topitem=facilities&a
       mp;breadCrumbSource="
       class="links2 ">Räume und Gebäude</a>
       &nbsp;&nbsp;&nbsp;&nbsp;
       </div>


       <div class="breadcrumb">
       Sie sind hier:
       <strong>Startseite</strong>


       <img src="/QIS/images/next.svg" alt="" border="0">
       <a class="regular" href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;c
       ategory=veranstaltung.browse&amp;navigationPosition=lectures%2Clectureindex&amp;breadcrum
       b=lectureindex&amp;topitem=lectures&amp;subitem=lectureindex">Veranstaltungsverzeichnis</a>
       </div>
       <div class="divcontent">



       \s
       <div id="makronavigation">\s
       <ul class="menue">\s





       <li class="menueListStyle">


       <a href="https://lsf.hhu.de/qisserver/rds?state=wtree&amp;search=1&amp;category=veranstalt
       ung.browse&amp;navigationPosition=lectures%2Clectureindex&amp;breadcrumb=lectureindex&amp
       ;topitem=lectures&amp;subitem=lectureindex" class="auflistung " target='_self'>Veranstalt
       ungsverzeichnis</a>
       </li>





       <li class="menueListStyle">


       <a href="https://lsf.hhu.de/qisserver/rds?state=change&amp;type=5&amp;moduleParameter=vera
       nstaltungSearch&amp;nextdir=change&amp;next=search.vm&amp;subdir=veranstaltung&amp;_form=di
       splay&amp;function=search&amp;clean=y&amp;category=veranstaltung.search&amp;navigationPosit
       ion=lectures%2CsearchLectures&amp;breadcrumb=searchLectures&amp;topitem=lectures&amp;subi
       tem=searchLectures" class="auflistung " target='_self'>Suche nach Veranstaltungen</a>
       </li>





       <li class="menueListStyle">


       <a href="https://lsf.hhu.de/qisserver/rds?state=currentLectures&amp;type=0&amp;next=Cur
       rentLectures.vm&amp;nextdir=ressourcenManager&amp;navigationPosition=lectures%2CcurrentL
       ectures&amp;breadcrumb=currentLectures&amp;topitem=lectures&amp;subitem=currentLectures&a
       mp;asi=" class="auflistung " target='_self'>Veranstaltungen - tagesaktuell</a>
       </li>





       <li class="menueListStyle">


       <a href="https://lsf.hhu.de/qisserver/rds?state=currentLectures&amp;type=1&amp;next=Curr
       entLectures.vm&amp;nextdir=ressourcenManager&amp;navigationPosition=lectures%2CcanceledL
       ectures&amp;breadcrumb=canceledLectures&amp;topitem=lectures&amp;subitem=canceledLecture
       s&amp;asi=" class="auflistung " target='_self'>Ausfallende Veranstaltungen</a>
       </li>
       <li class="menueListStyleCloseMenu">
       <a href="https://lsf.hhu.de/qisserver/rds?state=user&amp;type=9&amp;menu_open=n" class="
       auflistung " target='_self'>Navigation ausblenden</a>
       </li>
       </ul>
       &nbsp; </div>


       \s
       <div class="content">



       <a name="lese"></a>




       <form class="form" action="https://lsf.hhu.de/qisserver/rds?state=wplan&amp;search=ver&
       amp;act=add" method="post">

       </form>



       </div>
       <div style="clear: both;"></div>
       </div>
       \s
       <div style="padding-bottom: 7em;"></div>
       <div class="divfoot">
       <div class="divfoot_navigation">
       <a href="https://lsf.hhu.de/qisserver/rds?state=template&amp;template=about" class="link
       s3">Impressum und Datenschutz</a> |
       <a href="https://www.uni-duesseldorf.de/home/footer/datenschutz.html" class="links3">
       Datenschutz</a>
       <div style="float: right; padding-right: 10px; line-height: 20px;">capuma-lsf-prod-as04</div>

       </div>
       <div class="divfoot_logo">QIS, LSF und HISinOne sind Produkte der\s
       <img src="/QIS/images//his_logoklein.gif" alt="Heinrich Heine Universität Düsseldor
       f" border="0">
       eG
       </div>
       </div>


       <!-- Matomo -->
       <script type="text/javascript">
       var _paq = window._paq || [];
       /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
       _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
       _paq.push(['trackPageView']);
       _paq.push(['enableLinkTracking']);
       (function() {
       var u="//piwik.rz.uni-duesseldorf.de/piwik/";
       _paq.push(['setTrackerUrl', u+'matomo.php']);
       _paq.push(['setSiteId', '58']);
       var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
       g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentN
       ode.insertBefore(g,s);
       })();
       </script>
       <!-- End Matomo Code -->
       </div>
       <script type="text/javascript" src="/qisserver/resources/bower_components/jquery/dist/
       jquery.min.js"></script>
       <script type="text/javascript" src="/qisserver/pub/js/qis-00000001.js"></script>
       <script type="text/javascript" src="/qisserver/pub/js/qrCode.js"></script>   

       <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver_functions.js"><
       /script>
       <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver_language_init.js
       "></script>
       <script type="text/javascript" src="/qisserver/pub/js/lsfpageobserver.js"></script>

       <script src="/qisserver/pub//js/availability.js" type="text/javascript"></script>
       </body>
       </html>   
       """;
}
