version: "3.8"
services:
  database:
    image: mariadb:10.7
    ports:
      - "3306:3306" # port binding only for external access via IntelliJ
    environment:
      - "DB_USER=root"
      - "MARIADB_ROOT_PASSWORD=iamgroot"
      - "DB_HOST=database"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u$DB_USER', '-p$MARIADB_ROOT_PASSWORD' ]
      timeout: 20s
      interval: 20s
      retries: 10

  spring:
    image: chicken_spring
    build: --no-cache -t .
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=database"
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
